function false_info()
	local ln = level.name()
	if ln=="l03u_agr_underground" and has_info("yakut_false_start") then
		give_info("yakut_false_have")
	elseif ln=="l03_agroprom" and has_info("yakut_false_have") then
		give_info("yakut_false_done")
	elseif ln=="l06_rostok" and has_info("zahar_naemnik_start") then
		give_info("zahar_naemnik_begin")
	elseif ln=="l10u_bunker" and has_info("ucen_talk_need") then
		give_info("ucen_talk_spawn")
	elseif ln=="l01_escape" and has_info("prizrak_finalzver_start") then
		give_info("info_spawn_zver")
	end
end

function checking_use_item(obj)
	local ln = level.name()
	local sec = obj:section()
	if ln=="marsh" and sec=="sysh_flash" then
		create("a_inventory_box72",xyz(-113.72676086426,0.31462702155113,90.563606262207),39186,8380)
		give_info("treasure_sysh_start")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif ln=="l01_escape" and sec=="voen_document" then
		create("snp_kordon1",xyz(-96.201904296875,-4.6710577011108,-17.629180908203),166215,73)	-- snp
		give_info("bandranen_pda_need")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif ln=="jupiter" and sec=="pda_padlikova" then
		give_info("jup_zat_info")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif ln=="jupiter" and sec=="blocknot_saharova" then
        if not has_info("blocknot_saharova_have") then
            give_info("blocknot_saharova_have")
			buusty_dialog.upi_mercaushiy_sms2(db.actor,obj)
        end
	elseif ln=="l02_garbage" and sec=="bandranen_pda" then
		give_info("bandranen_pda_est")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="fraer_pda" and has_info("bandranen_pda_est") then
		give_info("prapor_talk_need")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif ln=="l07_military" and sec=="ara_flash" then
		give_info("ara_pda_est")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif ln=="l08_yantar" and sec=="zapiska_ranennogo"  then
		give_info("have_listok")
	elseif ln=="lost_village" and sec=="kapitan_pda"  then
		give_info("pda_bazar")
	elseif ln=="generators" and sec=="dosye_zvez"  then
		give_info("idu_na_nz")
--	elseif ln=="atp_for_test22" and sec=="disk_adren"  then
--		give_info("atp_banda_disk_spawn")
	elseif sec=="razved_karta" then
		give_info("otkput_march_perexod")
	elseif sec=="recipi_bpb" then
		give_info("info_artmod_probabka_burera")
	elseif sec=="stukach_book" then
		give_info("info_artmod_cristall_buzz")
	elseif sec=="arhara_listok" then
		give_info("perehod_chaes2_na_chaes")
	elseif sec=="bloknot_pantera" then
		give_info("perehod_warlab_na_gener")
	elseif sec=="new_document_sniper" then
		give_info("rebyta_domoy")
	elseif sec=="forest_last_dead_listok" then
		give_info("forest_psu_perex")
	elseif sec=="klenov_opisalovo" then
		give_info("posulku_poluchil")
	elseif sec=="korobka_sigars" then
		give_info("portal_lima_idu")
	elseif sec=="izomorf_kristal" then
		give_info("superzhekan_est")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="sniper_flash" then
		give_info("prizrak_zver_have")
	elseif sec=="iskra_listok" then
		give_info("tel_dcity_kanaliy")
	elseif sec=="mem_module" then
		give_info("perexody_otkryty")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="wa2000_izomorf" then
		give_info("snaiperka_est")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="5.45x39_izomorf" then
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="5.45x39_izomorf_1" then
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="7.62x54_izomorf" then
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="9x39_izomorf" and has_info("kod_vveden_verno") then
		give_info("dell_blok_tele")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="siv_pda" and has_info("ara_pda_est") then
		give_info("sah_talk_need")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	elseif sec=="ver" then
		give_info("agro_muxa_way1")
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	end
end

function actor_update(delta)
	check_npc_dead()
	check_ecolog_dead()
	dead_npc()
	check_info()
	new_info()
	kot_info()
	forest_info()
	grib_respawn()
	update_new()
	kot_update()
end

function dead_npc()
	if (has_info("esc_saha_dead") or has_info("dyak_dead")) and not has_info("dyak_help_done") then
		give_info("dyak_help_fail")
	elseif (has_info("add_church_ban1_dead") or has_info("add_church_ban2_dead") or has_info("add_church_ban3_dead")) then
		give_info("add_church_ban_signal")
	end

	if not has_info("marsh_band_spawn") then
		create("prov_ruk",xyz(-3.481797,3.3647267818451,12.3242),137219,3418)
       spawn_prohod()
       spawn_prohod_lim()
	   spawn_prohod_hos()
       give_info("marsh_band_spawn")
	end
end

function check_info()
	local rnd = math.random
	local ln = level.name()
	if has_info("brat_luis_have") and not has_info("brat_luis_killself") then
		timer("luis_killself",rnd(10,15),"braad_test.luis_killself()")
		give_info("brat_luis_killself")
    elseif ln == "marsh" and has_info("brat_luis_start") then
		give_info("brat_luis_spawn")
    elseif ln == "l07_military" and has_info("francuz_start") then
		give_info("francuz_spawn")
	end
end

function new_info()
	local ln = level.name()
	if ln == "l01_escape" and (has_info("xalyava_naemnik_see") or
has_info("xalyava_dead")) and not has_info("xalyava_nebo_have") then
		give_info("xalyava_nebo_fail")
	end
    if ln == "l03_agroprom" and has_info("kot_agro_mono_start")
and not has_info("kot_agro_mono_spawn")	then
		give_info("kot_agro_mono_spawn")
	end
    if (has_info("chuk_dead") or has_info("gek_dead")) and not has_info("kot_agro_mono_have") then
		give_info("kot_agro_mono_fail")
    end
end

function main_braad(npc)
npc:set_character_community("ecolog", 0, 0)
npc:set_relation(game_object.friend, db.actor)
give_info( "freeman_braad_one" )
end

function setGulagEnemy()
	local obj = server_object("rostok_stalker")
	create("wpn_mp5",obj.position,obj.m_level_vertex_id,obj.m_game_vertex_id,obj.id)
	create("wpn_val",obj.position,obj.m_level_vertex_id,obj.m_game_vertex_id,obj.id)
	ai:create_ammo("ammo_5.56x45_ss190",obj.position,obj.m_level_vertex_id,obj.m_game_vertex_id,obj.id,30)
end

function bloodsucker()
	create("bloodsucker_strong",xyz(147.087142945,-0.00357154117,59.948166),39508,1228)
	create("bloodsucker_strong",xyz(147.087142945,-0.00357154117,59.948166),39508,1228)
	create("bloodsucker_strong",xyz(147.087142945,-0.00357154117,59.948166),39508,1228)
end

function main_friend(npc)
npc:set_relation(game_object.friend, db.actor)
end

function zombie_blow()
	create("burer_strong",xyz(-108.363,21.564,-35.483),312,1529)
	create("m_poltergeist_dd",xyz(-108.363,21.564,-35.483),312,1529)
	create("bloodsucker_effector",xyz(-146.986,-19.088,-72.524),1082,1457)
	create("cat_strong",xyz(-85.379,-19.090,-49.233),9988,1495)
	create("cat_strong",xyz(-85.379,-19.090,-49.233),9988,1495)
	create("cat_strong",xyz(-85.379,-19.090,-49.233),9988,1495)
	create("cat_strong",xyz(-85.379,-19.090,-49.233),9988,1495)
	create("cat_strong",xyz(-86.602,-19.090,-171.465),9340,1455)
	create("cat_strong",xyz(-86.602,-19.090,-171.465),9340,1455)
end

function zasada_for()
	create("electro_chimera",xyz(12.886095046997,-16.55083847,175.3548889),320050,1697)
	create("new_electro_chimera",xyz(12.886095046997,-16.55083847,175.3548889),320050,1697)
	create("fire_chimera",xyz(12.886095046997,-16.55083847,175.3548889),320050,1697)
	create("chimera_x_ray",xyz(12.886095046997,-16.55083847,175.3548889),320050,1697)
end

function radar_man()
	create("m_controller_old_fat",xyz(-61.979244232178,-21.8962020874,35.8896102905),195,2727)
	create("m_controller_old",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_babka_normal",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_babka_strong",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_immortal",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_normal",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_normal",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_immortal",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_blow",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
	create("zombie_normal",xyz(0.86928582191467,-23.69577599,1.777916193),6155,2703)
end

function killactor (sid)
local npc = level_story_object (9623)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, db.actor)
local npc = level_story_object (9624)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, db.actor)
local npc = level_story_object (9625)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, db.actor)
local npc = level_story_object (9905)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:set_relation (game_object.enemy, db.actor)
end

function killactor_spawn()
	create("killer_boevik2",xyz(43.09783554,-8.13079166,14.410468),345215,1582)
	create("killer_boevik1",xyz(59.50757599,-8.5839643,9.3478708),358211,1570)
	create("killer_boevik3",xyz(59.52076721,-8.7670116,22.850177765),358227,1559)
	create("killer_boevik4",xyz(40.780555725,-8.319325447,19.2897949),343015,1582)
	create("killer_boevik5",xyz(46.9849434,-8.1420059,20.492004),348191,1582)
	create("killer_boevik6",xyz(51.40478897,-8.08700466,13.5054283),351374,1582)
end

function sorok_pda()
	return has("device_pda_npc",40)
end

function sorok_pda_sdal(first_speaker, second_speaker)
lost("device_pda_npc",40)
end		
			
function kill_npc(sid)
local npc = level_story_object (9630)
    if npc == nil or npc:alive () == false then
       return
    end
    npc:kill(npc)
end


function take_yakut_agro2_spot()
	sak.add_spot_of_docent(9650)
end


function new_comp()
	create("computer_new",xyz(27.945556640625,-6.619695186615,-14.894629478455),6746,1140)
end

function release_actor_items()
	give_info("biznes_remove_special_item")
	db.actor:iterate_inventory(
		function(dummy,item)
			-- Документы Воронина спецом вынесены отдельно, т.к. почему-то через protected_items 2 штуки все равно удалялись
			if item:section()~="zone_docs" and
				not protected_items.actor_items_keep(item:section()) then
				-- удаление вещи
				release(item)
			end
		end
	,db.actor)
	disable_info("biznes_remove_special_item")

	_G.Dream:sleep(5 + get_value("energy_drink", 0))
	create("medkit",xyz(66.125068664551,-8.0152215957642,16.54740524292),364537,1582)
	create("bread",xyz(66.125068664551,-8.0152215957642,16.54740524292),364537,1582)
end

function release_actor_money()
  local num = db.actor:money()
  db.actor:give_money(-num)
  game_stats.money_quest_update(-num)
end

function friendactor(community1, community2)
relation_registry.set_community_goodwill ("stalker", "actor", 1001)
end

function atak_larger_have(task, info)
  if has_info("snip_esc1_dead") and
	has_info("snip_esc2_dead") and
	has_info("snip_esc3_dead") and
	has_info("snip_esc4_dead") and
	has_info("snip_esc5_dead") and
	has_info("snip_esc6_dead")and
	has_info("snip_esc7_dead") and
	has_info("snip_esc8_dead") and
	has_info("snip_esc9_dead") and
	has_info("snip_esc10_dead") and
	has_info("snip_esc11_dead") and
	has_info("snip_esc12_dead") ~= nil then
		return give_info("atak_larger_have") ~= nil
  end
return false
end

function zahar_naemnik_have(task, info)
  if has_info("naem_zahar1_dead") and
	has_info("naem_zahar2_dead") and
	has_info("naem_zahar3_dead") and
	has_info("naem_zahar4_dead") and
	has_info("naem_zahar5_dead") and
	has_info("naem_zahar6_dead") ~= nil then
		return give_info("zahar_naemnik_have") ~= nil
  end
return false
end

function check_npc_dead()
    if has_info("marsh_dan_umer") and
		has_info("informator_pda_start") and not
		has_info("informator_pda_have") and not
		has_info("informator_pda_done") and not
		has_info("marsh_dan_umer_newsinfo1") then
			timer("sms_new",math.random(30,60),"braad_test.sms_new()")
            give_info("marsh_dan_umer_newsinfo1")
	end
	if has_info("marsh_dan_umer") and
		has_info("dan_grab_start") and
		has_info("dan_grab_have") and not
		has_info("dan_grab_done") and not
		has_info("marsh_dan_umer_newsinfo2") then
			timer("sms_new",math.random(40,70),"braad_test.sms_new()")
			give_info("marsh_dan_umer_newsinfo2")
	end
    if has_info("marsh_dan_umer") and
		has_info("dan_flash_start") and
		has_info("dan_flash_have")  and not
		has_info("dan_flash_done") and not
		has_info("marsh_dan_umer_newsinfo3") then
			timer("sms_new",math.random(40,70),"braad_test.sms_new()")
            give_info("marsh_dan_umer_newsinfo3")
	end
end

function sms_new()
--	give_info("sms_new_dan1")
	amk.send_tip(translate("sms_new_dan1_text"),nil,nil,30)
end

function check_ecolog_dead()
    if has_info("ucen_talk_est") and not
		has_info("marsh_dan_umer_newsinfo4") then
                timer("sms_new1",math.random(140,170),"braad_test.sms_new1()")
               give_info("marsh_dan_umer_newsinfo4")
	end
end

function sms_new1()
--	give_info("sms_new_dan2")
	amk.send_tip(translate("sms_new_dan2_text"),nil,nil,30)
end

function actor_has_money_30000()
  return has_money(30000)
end

function give_money_30000(t1,t2)
  lost_money(30000)
end

function delete_smart()
  local se_obj = server_object("esc2_bloodsucker1")
  if se_obj then
    release(se_obj, true)
  end
  local se_obj = server_object("ros_smart_stalker1")
  if se_obj then
    release(se_obj, true)
  end
end

function spawn_prohod()
    if not has_info("info_spawn_teleport") then
		local se_obj = create("zone_teleport_new",xyz(-208.9479,0.86408543,-291.8642),37124,3362)
		set_value("zone_teleport_new", se_obj.id)
		local se_obj = create("zone_teleport_new_out",xyz(34.4663,0.87717,-287.2317),156875,3436)
		set_value("zone_teleport_new_out", se_obj.id)
		give_info("info_spawn_teleport")
	end
end

function spawn_church_band()
	create("add_church_ban1",xyz(294.5813,7.1353683,-153.27551),327543,3531)
	create("add_church_ban2",xyz(294.5813,7.1353683,-153.27551),327543,3531)
	create("add_church_ban3",xyz(294.5813,7.1353683,-153.27551),327543,3531)
end

function sed_village()
	map_spot(server_object("marsh_small_nebo").id,"blue_location","sed_village_0")

end

function remove_village()
	del_map_spot(server_object("marsh_small_nebo").id,"blue_location")
end

-- правка вылета и неубирания худа при взятии рюкзака калмыка - перенесено в калбек на подъем
function mina_band(obj)
end
function mina_band2(obj)
	if obj:section()=="grenade_rgd5_new" then
		if level.main_input_receiver() then
			level.start_stop_menu(level.main_input_receiver(), true)
		end

		amk_particle.amk_particle({
			particle="explosions\\explosion_fuelcan",
			pos=db.actor:position(),
			sound=[[weapons\t_rgd5_explosion]]
		})

		local h = hit()
		h.draftsman = db.actor
		h.direction = vector():set(0,0,0)
		h:bone("bip01_spine")
		h.type = hit.explosion
		h.power = 1.8
		h.impulse = 500
		db.actor:hit(h)

		level.add_pp_effector("amk_shoot.ppe", 2011, false)
		level.add_pp_effector( "agr_u_fade.ppe", 8120804, false ) -- чтоб красивее было

		timer("run", 1, "braad_test.mina_band3()")
		release(snp.object_by_section_offline("prov_ruk"))
		braad_test.kalmyak_tele2()
	end
end
function mina_band3()
	release(server_object(db.actor:object("grenade_rgd5_new"):id()))
end

-- правка вылета и неубирания худа при взятии рюкзака калмыка - перенесено в калбек на подъем
function kalmyak_tele( actor, npc)
end
function kalmyak_tele2()
   give_info("teleport_started")
   level.add_pp_effector ("blink.ppe", 234, false)
   level.add_pp_effector("teleport.ppe", 2006, false)
   db.actor:set_actor_position(patrol("kalmyak_tele_walk"):point(0))
   local dir = patrol("kalmyak_tele_look"):point(0):sub(patrol("kalmyak_tele_look"):point(0))
   db.actor:set_actor_direction(-dir:getH())
   give_info("teleport_finished")
   give_info("kalmyak_vstreca_start")
end
------------------------------ НЕ ИСПОЛЬЗУЕТСЯ!
function delete_obj_restrictor()
  local se_obj = server_object("marsh_havan_restr")
  if se_obj then
    release(se_obj, true)
  end
end

function spawn_havan_restr2()
local se_obj = create("space_restrictor",xyz(-4.2143630981445,3.3634412288666,12.2967),136894,3418)
local custom = "[logic]\ncfg = scripts\\marsh\\marsh_havan_restr2.ltx"
rewrite_restrictor(se_obj, custom, 3.0)
end

local out_object
local in_object

function ograblen_kalm(actor,npc)
local inv_box_1 = level_story_object(14003)
out_object = db.actor
in_object = inv_box_1
give_info("biznes_remove_special_item")
db.actor:inventory_for_each(transfer_object_item)
disable_info("biznes_remove_special_item")
end

function vozvrat_kalm(actor,npc)
local inv_box_1 = level_story_object(14003)
in_object = db.actor
out_object = inv_box_1
give_info("biznes_remove_special_item")
out_object:inventory_for_each(transfer_object_item)
disable_info("biznes_remove_special_item")
end

function transfer_object_item(item)
out_object:transfer_item(item, in_object)
end
------------------------------ НЕ ИСПОЛЬЗУЕТСЯ!
function kalmyak_vrag(actor, npc)
    xr_gulag.setGulagEnemy ("kalmyak_marsh", actor)
end

function kalmyak_spawn()
local obj = create("kalmyak_ruk",xyz(-199.24903869629,0.60609865188599,130.58129),38203,3383)
   create_kalmyak_restr()
   set_kalmyak_ruk()
end

function create_kalmyak_restr()
	local se_obj = create("space_restrictor",xyz(-194.6745300293,0.58615601062775,133.2268),38203,3383)
	local custom = "[logic]\ncfg = scripts\\marsh\\mar_kalmyak_restr1.ltx"
	rewrite_restrictor(se_obj, custom, 3.0)
	local se_obj = create("space_restrictor",xyz(-190.16891479492,-0.44136956334114,125.738),38203,3383)
	local custom = "[logic]\ncfg = scripts\\marsh\\mar_kalmyak_restr2.ltx"
	rewrite_restrictor(se_obj, custom, 3.0)
	local se_obj = create("space_restrictor",xyz(-192.65054321289,-0.32059952616692,119.033),38203,3383)
	local custom = "[logic]\ncfg = scripts\\marsh\\mar_kalmyak_restr3.ltx"
	rewrite_restrictor(se_obj, custom, 3.0)
	local se_obj = create("space_restrictor",xyz(-201.21597290039,0.26242354512215,116.694),38203,3383)
	local custom = "[logic]\ncfg = scripts\\marsh\\mar_kalmyak_restr4.ltx"
	rewrite_restrictor(se_obj, custom, 3.0)
	local se_obj = create("space_restrictor",xyz(-206.72094726563,-0.32424575090408,123.919),37907,3383)
	local custom = "[logic]\ncfg = scripts\\marsh\\mar_kalmyak_restr5.ltx"
	rewrite_restrictor(se_obj, custom, 3.0)
	local se_obj = create("space_restrictor",xyz(-203.21374511719,-0.32538011670113,137.027),37907,3383)
	local custom = "[logic]\ncfg = scripts\\marsh\\mar_kalmyak_restr6.ltx"
	rewrite_restrictor(se_obj, custom, 3.0)
end


function set_kalmyak_ruk()
	map_spot(iterate_server_objects("box_kalmyak").id,"crlc_big","set_kalmyak_ruk_0")
end

function remove_kalmyak_ruk()
	del_map_spot(iterate_server_objects("box_kalmyak").id,"crlc_big")
end

function set_kalmyak()
	map_spot(server_object("kalmyak_marsh").id,"crlc_big","set_kalmyak_0")
end

function remove_kalmyak()
	del_map_spot(server_object("kalmyak_marsh").id,"crlc_big")
end

function kontr_marsh_restr()
	local se_obj = create("space_restrictor",xyz(-171.56242370605,0.78741002082825,391.19),56846,3371)
	local custom = "[logic]\ncfg = scripts\\new\\nebo\\kontr_marsh_restr1.ltx"
	rewrite_restrictor(se_obj, custom, 53.0)
	local se_obj = create("space_restrictor",xyz(-170.94248962402,1.1991214752197,404.29232),57320,3361)
	local custom = "[logic]\ncfg = scripts\\new\\nebo\\kontr_marsh_restr2.ltx"
	rewrite_restrictor(se_obj, custom, 53.0)
	local se_obj = create("space_restrictor",xyz(-192.83070373535,1.0270764827728,396.1445),45298,3361)
	local custom = "[logic]\ncfg = scripts\\new\\nebo\\kontr_marsh_restr3.ltx"
	rewrite_restrictor(se_obj, custom, 53.0)
	local se_obj = create("space_restrictor",xyz(-204.17848205566,0.53202784061432,404.1797),39196,3361)
	local custom = "[logic]\ncfg = scripts\\new\\nebo\\kontr_marsh_restr4.ltx"
	rewrite_restrictor(se_obj, custom, 53.0)
	local se_obj = create("space_restrictor",xyz(-189.07986450195,1.2418839931488,418.6262),46761,3361)
	local custom = "[logic]\ncfg = scripts\\new\\nebo\\kontr_marsh_restr5.ltx"
	rewrite_restrictor(se_obj, custom, 53.0)
	local se_obj = create("space_restrictor",xyz(-175.13674926758,1.3927493095398,423.0242),54657,3361)
	local custom = "[logic]\ncfg = scripts\\new\\nebo\\kontr_marsh_restr6.ltx"
	rewrite_restrictor(se_obj, custom, 53.0)
end

function set_red_contr()
	-- правка по потере мозга при сейв/лоаде.
	local se_obj = create("space_restrictor",xyz(-175.13674926,1.3927493095,423.02426147),54657,3361)
	local custom = "[logic]\nactive = sr_idle\n[sr_idle]\non_actor_inside = nil %=braad_test.spawn_red_contr%"
	rewrite_restrictor(se_obj, custom, 50)

	map_spot(server_object("marsh_controller").id,"crlc_big","set_red_contr_0")
end

function spawn_red_contr()
	create("kontrik_red_mozg",xyz(-175.13674926,1.3927493095,423.02426147),54657,3361)
	for i=1,3 do
		create("zombie_hell"..tostring(math.random(15)),xyz(-175.13674926,1.3927493095,423.02426147),54657,3361)
	end
end

function remove_red_contr()
	local obj = server_object("marsh_controller")
	if obj then
		del_map_spot(obj.id,"crlc_big")
	end
end

function kashei_spawn()
local obj = create("sveeblov_ruk",xyz(406.22711181641,3.4233021736145,236.834),407402,3546)
end

function set_kashei()
	map_spot(server_object("kashei").id,"blue_location","set_kashei_0")
end

function remove_kashei()
	del_map_spot(server_object("kashei").id,"blue_location")
end

function reregistr_kashei()
	netpacket:modify(server_object("kashei"), "custom_data", "[logic]\ncfg = scripts\\marsh\\mar_kashei_new.ltx", "story_id", 14100)
end

function friendactornebo(community1, community2)
	relation_registry.set_community_goodwill ("nebo", "actor", 100)
end


function kot_krovosos()
local position = db.actor:position()
	position.x = position.x + 25
local obj = create("bloodsucker_strong",position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
local obj = create("burer_strong",position, db.actor:level_vertex_id(), db.actor:game_vertex_id())
end

function spawn_blizn_krug1()
	local obj = server_object("blizn_krug1")
	create("mono_note",obj.position,obj.m_level_vertex_id,obj.m_game_vertex_id,obj.id)
end
------------------------------------------------------ищем монолитовцев вешаем метки------------------------------
function set_televizor()
	map_spot(server_object("marsh_pust_restr").id,"crlc_big","set_televizor_0")
set_televizor2()
set_televizor3()
set_televizor4()
set_televizor5()
end

function set_televizor2()
	map_spot(server_object("dog_marsh").id,"crlc_big","set_televizor2_0")
end

function set_televizor3()
	map_spot(server_object("bloodsuker_mar2").id,"crlc_big","set_televizor3_0")
end

function set_televizor4()
	map_spot(server_object("bloodsuker_mar3").id,"crlc_big","set_televizor4_0")
end

function set_televizor5()
	map_spot(server_object("marsh_zombi_hutor").id,"crlc_big","set_televizor5_0")
end

function remove_televizor()
	del_map_spot(server_object("marsh_pust_restr").id,"crlc_big")
remove_televizor2()
remove_televizor3()
remove_televizor4()
remove_televizor5()
end

function remove_televizor2()
	del_map_spot(server_object("dog_marsh").id,"crlc_big")
end

function remove_televizor3()
	del_map_spot(server_object("bloodsuker_mar2").id,"crlc_big")
end

function remove_televizor4()
	del_map_spot(server_object("bloodsuker_mar3").id,"crlc_big")
end

function remove_televizor5()
	del_map_spot(server_object("marsh_zombi_hutor").id,"crlc_big")
end

function set_kot()
	map_spot(server_object("kot").id,"crlc_big","set_kot_0")
end

function remove_kot()
	del_map_spot(server_object("kot").id,"crlc_big")
end

function set_giant()
	map_spot(server_object("gigant_red_strong1").id,"crlc_big","set_giant_0")
end

function remove_giant()
	del_map_spot(server_object("gigant_red_strong1").id,"crlc_big")
end


function luis_killself()
local npc
	for i=0,65534 do
        npc = level_object(i)
        if npc and npc:name() == "brat_luis" then
			npc:kill(npc)
			say([[weapons\colt\colt1911_shoot]])
			break
        end
    end
end

function francuz_killself()
local npc
	for i=0,65534 do
        npc = level_object(i)
        if npc and npc:name() == "francuz" then
			npc:kill(npc)
			say([[weapons\colt\colt1911_shoot]])
			break
        end
    end
end

function zahar_na_limansk()
  -- создается переход c АС В ЛИМАНСК
	if (not has_info(	"level_newlimansk" )) then
		local obj = create_lc(14101, vector():set(-304.5852,2.48176,428.14794),39639,1850,28633,3006,
			vector():set(7.2927484512329,-0.0087288916110992,-381.14739990234),
			vector():set(0.33175057172775,0,-0.94336712360382),"limansk",0)
		level_map_spot(obj.id, "level_changer1", "В Лиманск")
        give_info("level_newlimansk")
	end
end

function spawn_zombi_restr1()
    if level.name()=="limansk" and not has_info("lim_spawn_restr1") then
		create("lim_sniper",xyz(36.775608062744,28.541257858276,197.56105041504),46539,3003)
		create("lim_sniper_ohr1",xyz(3.7273268699,13.70157623291,196.73896789551),26776,3010)
		create("lim_sniper_ohr2",xyz(15.121144294,13.698766708374,196.21144104004),34620,3010)
		create("lim_sniper_ohr3",xyz(4.3583545684,17.090801239014,198.5705871582),27241,3010)
		create("zombi_restr1",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr2",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr3",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr4",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr5",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
    give_info("lim_spawn_restr1")
    end
end


function spawn_zombi_restr2()
    if level.name()=="limansk" and not has_info("lim_spawn_restr2") then
		create("zombi_restr1",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr2",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr3",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr4",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr5",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
    give_info("lim_spawn_restr2")
    end
end

function spawn_zombi_restr3()
    if level.name()=="limansk" and not has_info("lim_spawn_restr3") then
		create("zombi_restr1",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr2",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr3",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr4",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
		create("zombi_restr5",xyz(5.4863138198853,10.999716758728,155.81025695801),28057,3010)
    give_info("lim_spawn_restr3")
    end
end

function spawn_glushitel()
local obj = create("glushitel",xyz(-6.2885980606079,13.082293510437,195.33584594727),21733,3010)
end

function drop_actor(obj)
   if obj:section() == "glushitel" and has_info("borman_glushitel_restr") then
      give_info("borman_glushitel_have")
   end
end

function start(first_speaker, second_speaker)
	local actor, trader
	if db.actor and db.actor:id() == first_speaker:id() then
		actor = first_speaker
		trader = second_speaker
	else
		actor = second_speaker
		trader = first_speaker
	end
	lost("glushitel")
	local gtime = game.minutes()
	set_value("glushitel_reload", gtime + 300)
	clear_glushitel(actor)
end

function is_reload_ready(first_speaker, second_speaker)
	local gtime = game.minutes()
	local ftime = get_value("glushitel_reload", 0)
	if gtime >= ftime then
		return true
	else
		return false
	end
end

function is_reload_not_ready(first_speaker, second_speaker)
	local gtime = game.minutes()
	local ftime = get_value("glushitel_reload", 0)
	if gtime <= ftime then
		return true
	else
		return false
	end
end

function clear_glushitel(person)
	if person and person:object("glushitel") then
		release(server_object(person:object("glushitel"):id()), true)
	end
end

function clear_reload(first_speaker, second_speaker)
	del_value("glushitel_reload")
end

function start_kalmyak(first_speaker, second_speaker)
	local gtime = game.minutes()
	set_value("kalmyak_lekar", gtime + math.random(11, 12) * 60)
end

function is_lekar_ready(first_speaker, second_speaker)
	local gtime = game.minutes()
	local ftime = get_value("kalmyak_lekar", 0)
	if gtime >= ftime then
		return true
	else
		return false
	end
end

function is_lekar_not_ready(first_speaker, second_speaker)
	local gtime = game.minutes()
	local ftime = get_value("kalmyak_lekar", 0)
	if gtime <= ftime then
		return true
	else
		return false
	end
end

function clear_lekar(first_speaker, second_speaker)
	del_value("kalmyak_lekar")
end

function set_xalyava()
	map_spot(server_object("esc_xalyava").id,"crlc_big","set_xalyava_0")
end

-- Нейтралим наймов и чн с военными, чтобы не мешали
function begin_xalyava()
    local obj
	for a=1,8 do
        obj = server_object("xalyava_naem"..a)
        if obj then
			relation_registry.set_community_goodwill("military", obj.id, 5000)
	    end
	end
	obj = server_object("xalyava")
	if obj then
		relation_registry.set_community_goodwill("military", obj.id, 5000)
    end
	obj = server_object("xalyava_drug")
	if obj then
		relation_registry.set_community_goodwill("military", obj.id, 5000)
    end
end

function remove_xalyava()
	del_map_spot(server_object("esc_xalyava").id,"crlc_big")
end

function speech_xalyava()
sms("%c[sender]"..translate("name_halyava")..":\\n%c[sms_red]"..translate("sms_xalyava_speech_xalyava_0"), nil, nil, 60000, nil, [[sms\xalyava\speech_xalyava]])
end
-----------------------------turell---------------------------------------------------
function test_turrel()
local info_name = "info_turret_escape_spawn"
   if (get_value(info_name, false) == false) and
   (level:name() == "l01_escape") then
   set_value(info_name, true)
turret_mgun.create_turret("turret_nato",level_name, vector():set(-201.338,-20.307,-147.54),"bandit", "", 200,100) end
end

function turrel()
    turret_mgun.create_turret("turret_army", "l01_escape", vector():set(-191.44,-18.49,-151.513),62977,46, "military", "esc_blokpost", 120, 90)
end

function alife_dir(section,position,levelvertex,gamevertex,direction)
	local obj = create(section,position,levelvertex,gamevertex)
--    level_map_spot(obj.id, "TRENOGA", "")
	map_spot(obj.id,"crlc_big","alife_dir_0")
end

function lim_turrel()
    if not has_info("lim_spawn_lim_turrel") then
alife_dir("trenoga_lim1",vector():set(61.824359893799,14.957581520081,246.21290588379),58766,3021,
          vector():set(0.17578122019768,0,0.98442924022675))
    give_info("lim_spawn_lim_turrel")
    end
end

-----------------------------turell---------------------------------------------------

function kot_info()
	local rnd = math.random
	local ln = level.name()
    if (has_info("kot_kalmyak_lekar_done") or has_info("kot_holod_lekar_done")) and not has_info("kot_lekar_done")	then
give_info("kot_lekar_done")
    elseif ln == "l11_pripyat" and has_info("kot_find_rabi_scromnyi") and not has_info("kot_find_rabi_spawn_rabi") then
give_info("kot_find_rabi_spawn_rabi")
    elseif has_info("black_doctor_finish_dialog") and not has_info("black_doctor_delete") then
		timer("delete_black_doctor",rnd(10,15),"braad_test.delete_black_doctor()")
give_info("black_doctor_delete")
     elseif ln == "red_forest" and (has_info("shadowman_zver_have") or has_info("shadowman_zver_fail"))  and not has_info("shadowman_all") then
give_info("shadowman_all")
    end
end

function drink_vodka()
	db.actor:eat(db.actor:object("vodka"))
end

function rereg_scromnyi()
    if not has_info("scromnyi_rereg") then
	   logig_scromnyi()
       give_info("scromnyi_rereg")
    end
end


function logig_scromnyi()
	netpacket:modify(server_object("scromnyi"), "custom_data", "[logic]\ncfg = scripts\\mil\\mil_scromnyi_new.ltx", "story_id", 14102)
end

function rabi_mad()
local npc
	for i=0,65534 do
        npc = level_object(i)
        if npc and npc:alive() and npc:name() == "rabi" then
			npc:set_character_community("zombied", 0, 0)
			break
        end
    end
end

function spawn_prohod_lim()
    if not has_info("info_spawn_lim_teleport") then
local se_obj = create("lim_zone_teleport1",xyz(40.821,11.0686,215.0173),48310,3020)
set_value("lim_zone_teleport1", se_obj.id)
local se_obj = create("lim_zone_teleport2",xyz(49.1074,2.948,300.0252),51380,3022)
set_value("lim_zone_teleport2", se_obj.id)
    give_info("info_spawn_lim_teleport")
	end
end

function drop_lim(obj)
   if obj:section() == "nebo_clear" and has_info("nebo_kurier_del") then
       del_lim()
      release(server_object(obj:id()))
--	  amk.remove_item(obj)
   end
end


function del_lim()
    if not has_info("info_del_lim_teleport") then
local obj_id = get_value("lim_zone_teleport1", -1, true)
local se_obj = server_object(obj_id)
        if se_obj then
          release(se_obj, true)
        end
local obj_id = get_value("lim_zone_teleport2", -1, true)
local se_obj = server_object(obj_id)
        if se_obj then
          release(se_obj, true)
        end
	give_info("info_del_lim_teleport")
	end
end

function speech_teleport()
sms("%c[sender]"..translate("name_sviblov")..":\\n%c[sms_red]"..translate("speech_teleport_0_0"),nil,nil,20000)
give_info("nebo_kurier_first")
end

function kurier_dead()
local npc
	for i=0,65534 do
        npc = level_object(i)
        if npc and npc:name() == "nebo_kurier" then
			npc:kill(npc)
			break
        end
    end
end

function kurier_health(obj)
	if db.actor.health < 1 then
	    db.actor.health = db.actor.health + 0.6
	end
end

function eat_aptec()
	db.actor:eat(db.actor:object("medkit_scientic"))
end

function eat_antirad()
	db.actor:eat(db.actor:object("antirad"))
end

function doctor_dal()
got("medkit_scientic",1)
got("antirad",1)
end

function spawn_prohod_hos()
    if not has_info("info_spawn_hos_teleport") then
		create("hos_zone_teleport1",xyz(-86.273,25.844,674.829),3736,3044)
		create("hos_zone_teleport2",xyz(-104.113,34.25,615.65),127,3028)
		create("hos_zone_teleport3",xyz(-92.780,33.493,719.939),1801,3034)
		give_info("info_spawn_hos_teleport")
	end
end

function delete_black_doctor()
  local se_obj = server_object("black_doctor")
  if se_obj then
    release(se_obj, true)
  end
end

function spawn_shadowman()
local obj = create("shadowman_ruk",xyz(23.914667129517,3.9985284805298,26.488586425781),80890,3263)
end


function speech_shadowman()
sms("%c[sender]"..translate("name_shedoumen")..":\\n%c[sms_red]"..translate("speech_shadowman_0_0"),nil,nil,20000)
end

function shadowman_red_spn1()
    if not has_info("shadowman_red_spn1") then
	create("boar_normal_sh1",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh2",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh3",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh4",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh5",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("snork_normal_sh1",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh2",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh3",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh4",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh5",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
    give_info("shadowman_red_spn1")
	end
end

function shadowman_red_spn2()
    if not has_info("shadowman_red_spn2") then
	create("boar_normal_sh6",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh7",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh8",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh9",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh10",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("snork_normal_sh6",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh7",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh8",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh9",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh10",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
    give_info("shadowman_red_spn2")
	end
end

function shadowman_red_spn3()
    if not has_info("shadowman_red_spn3") then
	create("boar_normal_sh11",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh12",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh13",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh14",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("boar_normal_sh15",xyz(-9.1997413635254,0.043906480073929,-36.546310424805),60673,3290)
	create("snork_normal_sh11",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh12",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh13",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh14",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
	create("snork_normal_sh15",xyz(-22.176950454712,0.78433322906494,18.689910888672),49490,3263)
    give_info("shadowman_red_spn3")
	end
end


function forest_info()
    if level.name()=="red_forest" and not has_info("actor_in_forest") then
give_info("actor_in_forest")
    elseif has_info("mitya_dead") and not has_info("klyak_forest_doc_have") and not has_info("mitya_dead_sms") then
    timer("mitya_sms",math.random(180,200),"braad_test.mitya_sms()")
give_info("mitya_dead_sms")
    elseif level.name()=="marsh" and has_info("grab_stal1_dead") and has_info("grab_stal2_dead") and has_info("grab_stal3_dead") and has_info("grab_stal4_dead") and has_info("grab_stal5_dead") then
give_info("grab_stal_deads")
   end
end
--------------------------------------------------------ГРИБЫ---------------------------------------------------------------
local points={
{position={x=-284.4497,y=-18.2044,z=193.8524},gv=1789,lv=56319}, ---склады
{position={x=-355.6864,y=-3.100588,z=151.18237},gv=1793,lv=4240},  ---склады
{position={x=-269.84619,y=-11.2427,z=-71.7646},gv=10,lv=3200},  -- кордон
{position={x=-201.4213,y=-7.3733,z=-45.88},gv=68,lv=51172},  -- кордон
{position={x=-174.16,y=-3.36,z=-13.652},gv=69,lv=76187},  -- кордон
{position={x=-100.404,y=3.5878,z=77.947},gv=81,lv=160506},  -- кордон
{position={x=-52.189,y=4.272,z=250.807},gv=173,lv=227393},  -- кордон
{position={x=32.6452,y=1.899,z=383.063},gv=173,lv=227393},  -- кордон
{position={x=465.1087,y=1.222,z=-178.309},gv=3554,lv=451363},  -- marsh
{position={x=399.41339,y=0.3934,z=-169.761},gv=3547,lv=402755},  -- marsh
{position={x=342.558,y=8.3023,z=-108.475},gv=3533,lv=357939},  -- marsh
{position={x=272.111,y=0.548,z=-43.373},gv=3526,lv=310746},  -- marsh
{position={x=291.1808,y=0.548,z=36.855},gv=3527,lv=325573},  -- marsh
{position={x=367.14099,y=1.8678,z=161.486},gv=3539,lv=376678},  -- marsh
{position={x=387.748,y=3.5888,z=287.368},gv=3540,lv=393779},  -- marsh
{position={x=297.117,y=1.696,z=288.828},gv=3529,lv=329916},  -- marsh
{position={x=205.688,y=0.727,z=285.857},gv=3499,lv=262506},  -- marsh
{position={x=173.0422,y=1.435,z=355.277},gv=3491,lv=238394},  -- marsh
{position={x=214.362,y=0.6504,z=412.3115},gv=3488,lv=268283},  -- marsh
{position={x=217.9902,y=7.394,z=516.679},gv=3485,lv=270887},  -- marsh
{position={x=142.997,y=0.535,z=-248.0656},gv=684,lv=374191},  -- agroprom
{position={x=70.2182,y=-0.972,z=-234.066},gv=433,lv=305517},  -- agroprom
{position={x=63.0578,y=-1.14418,z=-149.503},gv=641,lv=299132},  -- agroprom
{position={x=-74.09,y=0.466,z=58.15},gv=528,lv=166791},  -- agroprom
{position={x=-29.9080,y=2.2372,z=103.523},gv=588,lv=210656},  -- agroprom
{position={x=12.6909,y=2.3448,z=92.3616},gv=476,lv=252867},  -- agroprom
{position={x=81.1135,y=16.0997,z=132.682},gv=508,lv=316629},  -- agroprom
{position={x=106.297,y=13.690,z=125.696},gv=508,lv=340894},  -- agroprom
{position={x=123.6996,y=10.369,z=165.9576},gv=504,lv=357641},  -- agroprom
{position={x=85.8348,y=10.5479,z=188.9713},gv=686,lv=321367},  -- agroprom
{position={x=319.6008,y=-47.9699,z=-195.063},gv=2082,lv=76027},  -- radar
{position={x=316.0666,y=-48.0291,z=-133.312},gv=2092,lv=74170},  -- radar
{position={x=307.758,y=-50.2595,z=-245.0376},gv=2078,lv=69567},  -- radar
{position={x=308.800,y=-49.135,z=-315.755},gv=2073,lv=69851},  -- radar
{position={x=372.8744,y=-51.6907,z=-344.82},gv=2068,lv=105583},  -- radar
{position={x=419.1445,y=-49.5586,z=-310.8674},gv=2066,lv=133749},  -- radar
{position={x=352.3292,y=-47.796,z=-115.3638},gv=2093,lv=94080},  -- radar
{position={x=395.896,y=-52.4274,z=-92.122},gv=2036,lv=122268},  -- radar
{position={x=440.01821,y=-49.07274,z=-55.515},gv=2038,lv=143343},  -- radar
{position={x=380.7494,y=-48.7936,z=-231.103},gv=2102,lv=111292},  -- radar
{position={x=422.2033,y=-55.075,z=-259.047},gv=2106,lv=135222},  -- radar
{position={x=466.6009,y=-48.3848,z=-219.513},gv=2059,lv=153140},  -- radar
{position={x=487.1975,y=-49.9339,z=-185.659},gv=2056,lv=160751},  -- radar
{position={x=109.0610,y=-0.6083,z=23.1811},gv=909,lv=305618},  -- darkvalley
{position={x=161.0832,y=6.02887,z=-9.5908},gv=916,lv=361563},  -- darkvalley
{position={x=177.67697,y=0.0723,z=-80.587},gv=919,lv=378637},  -- darkvalley
{position={x=140.8797,y=0.14625,z=-210.068},gv=927,lv=338700},  -- darkvalley
{position={x=174.1159,y=8.4689,z=-420.6929},gv=941,lv=374683},  -- darkvalley
{position={x=156.46878,y=4.2590,z=-467.606},gv=941,lv=356378},  -- darkvalley
{position={x=93.6686,y=1.662,z=-469.5579},gv=949,lv=288081},  -- darkvalley
{position={x=18.3328,y=1.2652,z=-453.902},gv=952,lv=195541},  -- darkvalley
{position={x=-76.9337,y=-0.73359,z=-395.521},gv=839,lv=83950},  -- darkvalley
{position={x=-129.5605,y=0.86102,z=-344.974},gv=845,lv=28054},  -- darkvalley
{position={x=-131.9178,y=-0.8644,z=-276.884},gv=848,lv=26173},  -- darkvalley
{position={x=203.9575,y=4.3727,z=203.835},gv=2885,lv=351940},  -- puzir
{position={x=182.1907,y=14.3156,z=168.909},gv=2885,lv=335133},  -- puzir
{position={x=106.863,y=4.8457,z=141.5648},gv=2885,lv=274853},  -- puzir
{position={x=60.0144,y=-0.001477,z=108.286},gv=2885,lv=238003},  -- puzir
{position={x=46.0673,y=-0.0032,z=57.7905},gv=2885,lv=226374},  -- puzir
{position={x=-9.9488,y=11.51488,z=-12.7767},gv=2882,lv=180062},  -- puzir
{position={x=54.212,y=8.6488,z=-83.8907},gv=2884,lv=232601},  -- puzir
{position={x=99.8832,y=0.12282,z=-94.3717},gv=2884,lv=269168},  -- puzir
{position={x=102.5485,y=-0.00115,z=-136.3648},gv=2884,lv=270778},  -- puzir
{position={x=-310.1566,y=-8.9571,z=30.3318},gv=2889,lv=338006},  -- aver
{position={x=-249.7383,y=-27.5183,z=127.1921},gv=2893,lv=441876},  -- aver
{position={x=-254.2902,y=11.043003,z=-3.8713},gv=2893,lv=434616},  -- aver
{position={x=-165.4225,y=26.00623,z=6.20755},gv=2894,lv=585369},  -- aver
{position={x=-94.820632,y=17.82067,z=39.2792},gv=2894,lv=708197},  -- aver
{position={x=4.8559,y=-45.3861,z=111.9942},gv=2895,lv=873123},  -- aver
{position={x=43.3978,y=-39.5448,z=166.2731},gv=2895,lv=943483},  -- aver
{position={x=109.7717,y=-40.9248,z=260.0759},gv=2899,lv=1062136},  -- aver
{position={x=217.1144,y=1.8175,z=186.544},gv=2901,lv=1250174},  -- aver
{position={x=-27.02234,y=-0.8796,z=-294.626},gv=3274,lv=44437},  -- red_forest
{position={x=17.7548,y=1.2997,z=-98.825},gv=3288,lv=77292},  -- red_forest
{position={x=-4.83979,y=0.2346,z=-155.3056},gv=3282,lv=64796},  -- red_forest
{position={x=7.52476,y=-2.52619,z=-265.6032},gv=3291,lv=71635},  -- red_forest
{position={x=100.37268,y=-1.5567,z=-290.506},gv=3300,lv=101983},  -- red_forest
{position={x=177.61671,y=-1.304368,z=-290.01339},gv=3314,lv=118739},  -- red_forest
{position={x=179.43177,y=-1.16113,z=-46.8759},gv=3317,lv=119698},  -- red_forest
{position={x=193.84136,y=-4.73345,z=10.9854},gv=3317,lv=126615},  -- red_forest
{position={x=215.8037,y=1.2874,z=102.9057},gv=3319,lv=137614},  -- red_forest
{position={x=194.8108,y=-1.7354,z=62.4528},gv=3318,lv=127327}  -- red_forest
}

function grib_respawn()
local timeh =level.get_time_hours()
local times =level.get_time_minutes()
    if (timeh == 22 and times == 1)  then
        if not has_info("info_respawn_grib") then
		   del_mushroom()
           spawn_grib()
		   give_info("info_respawn_grib")
		end
    end
    if (timeh == 23 and times == 1) then
        disable_info("info_respawn_grib")
    end
end

function spawn_grib()
	local rnd = math.random
	for i = 1,28,1 do
	    local a = points[rnd(#points)]
		create("mushroom", xyz(a.position.x, a.position.y, a.position.z), a.lv, a.gv)
end

end

function del_mushroom()
	local actorpos = db.actor:position()
	iterate_server_objects("mushroom", function(obj)
		if obj.parent_id == 65535 and obj.position:distance_to(actorpos) > 30 then
			release(obj)
		end
		return true
	end)
end
--------------------------------------------------------ГРИБЫ---------------------------------------------------------------

function set_green()
	map_spot(server_object("green_forest").id,"crlc_big","set_green_0")
end

function remove_green()
	del_map_spot(server_object("green_forest").id,"crlc_big")
end

function grab_set1(actor, npc)
    xr_gulag.setGulagEnemy ("grab_mitya_marsh", actor)
end

function grab_set11()
local npc
    for i=0,65534 do
    npc = level_object(i)
		if npc and npc:alive() and npc:name() == "grab_stal1" then
		    npc:set_character_community("bandit", 0, 0)
			break
		end
	end
	grab_set2()
	grab_set3()
	grab_set4()
	grab_set5()
end



function grab_set2()
local npc
    for i=0,65534 do
    npc = level_object(i)
		if npc and npc:alive() and npc:name() == "grab_stal2" then
		    npc:set_character_community("bandit", 0, 0)
			break
		end
	end
end

function grab_set3()
local npc
    for i=0,65534 do
    npc = level_object(i)
		if npc and npc:alive() and npc:name() == "grab_stal3" then
		    npc:set_character_community("bandit", 0, 0)
			break
		end
	end
end

function grab_set4()
local npc
    for i=0,65534 do
    npc = level_object(i)
		if npc and npc:alive() and npc:name() == "grab_stal4" then
		    npc:set_character_community("bandit", 0, 0)
			break
		end
	end
end

function grab_set5()
local npc
    for i=0,65534 do
    npc = level_object(i)
		if npc and npc:alive() and npc:name() == "grab_stal5" then
		    npc:set_character_community("bandit", 0, 0)
			give_info("klyak_forest_doc_scene")
			break
		end
	end
end

function mitya_kill()
local npc
	for i=0,65534 do
        npc = level_object(i)
        if npc and npc:alive() and npc:name() == "mitya" then
			npc:kill(npc)
			say([[weapons\colt\colt1911_shoot]])
			break
        end
    end
end

function mitya_sms()
sms("%c[sender]"..translate("name_sidorovich")..":\\n%c[sms_red]"..translate("sms_sidor_mitya_sms_0"), nil, nil, 30000, nil, [[sms\sidor\mitya_sms]])
give_info("mitya_dead_sms_sidor")
end

function spawn_green()
	create("green_ruk",xyz(228.335338,-7.298178,67.8218),143611,3319)
end

function clear_actor(npc)
    local npc = db.actor
    npc:iterate_inventory(__del_item, npc)
	friendactorstalker(community1, community2)
end

function __del_item(npc, item)
    local section = item:section()

    if protected_items.actor_items_keep(section) == true then
        return false
    end
    release(server_object(item:id()), true)
end

function friendactorstalker(community1, community2)
relation_registry.set_community_goodwill ("stalker", "actor", 400)
relation_registry.set_community_goodwill ("green", "actor", 100)
end

function actor_has_money_50000()
  return has_money(50000)
end

function give_money_50000(t1,t2)
  lost_money(50000)
end

function actor_has_money_10000()
  return has_money(10000)
end

function give_money_10000(t1,t2)
  lost_money(10000)
end

function speech_test()
--sms("ЖОПАААААААААААААААААААААААААААААААААААА",nil,nil,60000)
--give_info("mitya_dead_sms_sidor")
end

function kot_update()
    if level.name()=="l05_bar" and has_info("kot_need_next_done") and not has_info("bkot_spawn") then
		del_kot_marsh()
    end
end

function del_kot_marsh()
local se_obj = server_object("kot")
  if se_obj then
    release(se_obj, true)
	give_info("bkot_spawn")
  end
end

function spawn_zombi_forest()
    if not has_info("info_contr_spawn") then
		create("zombie_beee",xyz(-139.66778564453,-6.2611632347107,-57.55558013916),7320,3240)
		create("zombie_beee",xyz(-139.66778564453,-6.2611632347107,-57.55558013916),7320,3240)
		create("zombie_beee",xyz(-139.66778564453,-6.2611632347107,-57.55558013916),7320,3240)
		create("zombie_beee",xyz(-166.70251464844,2.2021112442017,-43.638122558594),4559,3240)
		create("zombie_beee",xyz(-166.70251464844,2.2021112442017,-43.638122558594),4559,3240)
		create("zombie_beee",xyz(-166.70251464844,2.2021112442017,-43.638122558594),4559,3240)
		create("zombie_beee",xyz(-150.7121887207,2.2457160949707,-32.752670288086),6685,3240)
		create("zombie_beee",xyz(-150.7121887207,2.2457160949707,-32.752670288086),6685,3240)
		create("zombie_beee",xyz(-150.7121887207,2.2457160949707,-32.752670288086),6685,3240)
    give_info("info_contr_spawn")
   end
end

function update_new()
forest_update()
end

function forest_update()
	local ln = level.name()
    if ln == "red_forest" and has_info("contr_forest1_dead") and has_info("contr_forest2_dead")	then
give_info("contr_forest_deads")
    end
	if ln == "red_forest" and has_info("denis_wound_start") and has_info("forest_wound_dead") and
	not has_info("denis_wound_next") then
give_info("denis_wound_fail")
    end
end

function spawn_denis()
	create("killer_denis1",xyz(-154.03199768066,2.179135799408,-29.984512329102),6074,3240)
	create("killer_denis2",xyz(-168.93768310547,2.1791498661041,-25.87652015686),4320,3240)
	create("killer_denis3",xyz(-153.88787841797,2.1781146526337,-38.099498748779),6064,3240)
	create("killer_denis4",xyz(-150.86233520508,2.3751785755157,-45.025329589844),6540,3240)
	create("killer_denis5",xyz(-157.27326965332,2.2941052913666,-50.785617828369),5652,3240)
	create("killer_denis6",xyz(-115.58462524414,2.3102631568909,-55.957679748535),9854,3240)
	create("killer_denis7",xyz(-112.0415725708,2.3187811374664,-54.043090820313),10286,3240)
	create("killer_denis8",xyz(-103.67635345459,2.3016946315765,-56.758888244629),11667,3250)
	create("killer_denis9",xyz(-164.65612792969,2.2453947067261,-42.774707794189),4821,3240)
end


function set_tunel()
	map_spot(server_object("contr_forest_restr").id,"crlc_big","set_tunel_0")
end

function remove_tunel()
	del_map_spot(server_object("contr_forest_restr").id,"crlc_big")
end

function spawn_ag_restr()
local se_obj = create("space_restrictor",xyz(-163.7038269043,0.33191874623299,-299.45358276367),73168,447)
local custom = "[logic]\ncfg = scripts\\agr\\agr_restr.ltx"
rewrite_restrictor(se_obj, custom, 60.0)
end

--function spawn_blizn_krug_dead()
--local obj = create("mono_dead_doc",xyz(245.210,4.360,55.923),292294,3516)
--end

function gener_na_boloto_vert()
  -- вертушечный переход1
	if (not has_info(	"gener_na_boloto" )) then
create_lc(18100, vector():set(-104.6570892334,37.470596313477,-467.96307373047),214585,3096,
208062,3484,
        vector():set(237.60340881348,26.244289398193,621.69653320313),
        vector():set(0,0,0),"marsh",1)
        end
end

function boloto_na_gener_vert()
  -- вертушечный переход2
	if (not has_info(	"boloto_na_gener" )) then
create_lc(18101, vector():set(345.39685058594,7.8543429374695,-69.320671081543),360152,3528,
216969,3096,
        vector():set(-102.54923248291,37.5275001525879,-466.853424072266),
        vector():set(0,0,0),"generators",1)
        end
end

function sarcofag_derevny()
  -- фото-переход
	if (not has_info(	"sarcofag_derevny" )) then
create_lc(18109, vector():set(-21.340265274048,69.629508972168,-31.520132064819),598,2417,
35739,3335,
        vector():set(73.263496398926,2.371077299118,-67.258171081543),
        vector():set(0,0,0),"lost_village",1)
        end
end


function control_monol_svalka()
  -- молния-переход
	if (not has_info("control_monol_svalka" )) then
create_lc(18110, vector():set(0.076748996973038,-34.357418060303,17.889852523804),1757,2512,
137004,319,
        vector():set(-57.10103225708,17.666576385498,17.847587585449),
        vector():set(0,0,0),"l02_garbage",0)
        end
end

function saxar_perexod()
  -- Сахар-переход
	if (not has_info("saxar_perexod" )) then
create_lc(18111, vector():set(-111.25610351563,1.9637259244919,-289.08743286133),3983,1486,
7244,1543,
        vector():set(-49.463424682617,27.120641708374,-11.838829040527),
        vector():set(0,0,0),"l08u_brainlab",1)
        end
end

function mozg_yantar()
  -- мозг-переход
	if (not has_info("mozg_yantar" )) then
create_lc(18112, vector():set(-45.602458953857,18.978830337524,-12.382658958435),2892,1530,
62547,1505,
        vector():set(45.247611999512,9.7975540161133,-59.355667114258),
        vector():set(0,0,0),"l08_yantar",1)
        end
end

function BitvaKL_rukzak()
	local obj = create("bitvakl_ruk",xyz(201.8493347168,-2.1620719432831,-79.324325561523),129996,3316)
end

function checking_taken_item60(obj)
  if obj:section()=="bitvakl_pda" then
    if not has_info("bitvakl_xvatit_spawn") then
	  give_info("bitvakl_xvatit_spawn")
	  say([[monsters\controller\controller_script_attack_0]])

	  amk.drop_item(db.actor,obj)
	  amk.remove_item(obj)

	  this.bitvakl_spawn()
	  spawn_restrictor.bitvakl_sr1()
	end
  end
end

local klpoints={
    {
        position={x=179.3902130127,y=-2.5856237411499,z=-67.094398498535},
        gv=3316,
        lv=119687
        },
    {
        position={x=232.40454101563,y=-1.7396693229675,z=-57.155769348145},
        gv=3316,
        lv=145476
        },
    {
        position={x=261.00622558594,y=-1.1188377141953,z=-96.045272827148},
        gv=3315,
        lv=156751
        },
    {
        position={x=237.57501220703,y=-4.7059030532837,z=-143.82832336426},
        gv=3315,
        lv=147314
        },
    {
        position={x=198.4962310791,y=-7.1063375473022,z=-139.28036499023},
        gv=3315,
        lv=129206
        },
    {
        position={x=200.56958007813,y=-6.1743240356445,z=-40.731639862061},
        gv=3317,
        lv=130430
        },
    {
        position={x=171.90243530273,y=-3.933501958847,z=-113.88834381104},
        gv=3315,
        lv=116166
        }
}
function bitvakl_spawn()
    local a, se_obj
	sms("%c[sender]"..translate("name_istochnik_neizvesten")..":\\n%c[sms_red]"..translate("sms_net_bitvakl_spawn_0"), nil, nil, 30000, nil, [[sms\net\bitvakl_spawn]])
	se_obj = create("af_blood_green",xyz(220.36111450195,-11.267262458801,-101.5218963623),138102,3315)
	for i=1,table.getn(klpoints) do
		a = klpoints[i]
		se_obj = create("m_controller_normal", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
		for i=1,1 do
			se_obj = create("zombie_normal", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
			se_obj = create("zombie_hell10", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
			se_obj = create("zombie_hell11", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
			se_obj = create("zombie_hell12", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
			se_obj = create("zombie_hell13", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
			se_obj = create("zombie_immortal", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
		end
	end
end

function lima_dead_city()
  	if (not has_info("lima_dead_city" )) then
-- Закрытие чита с проноской оружия в МГ
--create_lc(18113, vector():set(-51.921474456787,-10.597856521606,-182.62138366699),2891,2993,
create_lc(18113, db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),
100962,3593,
        vector():set(-239.38876342773,-2.0321259498596,300.58901977539),
        vector():set(0,-2,0),"dead_city",1)
        end
end

function dead_city_atpeshka()
  	if (not has_info("dead_city_atpeshka" )) then
		local obj = create_lc(18114, vector():set(72.183212280273,-1.8766392469406,-207.6682434082),425926,3646,
			368029,2813,
			vector():set(-6.6572103500366,-2.087566614151,-367.70422363281),
			vector():set(0,0,0),"atp_for_test22",1)
		level_map_spot(obj.id, "level_changer3", "На АТП")
        give_info("dead_city_atpeshka")
    end
end

function gar_pri1()
      -- создается переход с НЗ в Восточную Припять - не используется.
	if (not has_info(	"info_gar_pri1" )) then
		local obj = create_lc(130000, vector():set(425.775400878906,35.9266540527344,252.611056884766),1640838,2906,403978,3767,
			vector():set(-144.297119140625,0.4970370024442673,-404.1590270996094),
			vector():set(0,0,0 ),"pripyat",0)
        level_map_spot(obj.id, "level_changer1", "В Восточную Припять")
        give_info("info_gar_pri1")
	end
end

function yan_pri1()
      -- создается переход с Янтаря в Восточную Припять
	if (not has_info(	"info_yan_pri1" )) then
		local obj = create_lc(131000, vector():set(-253.81935119629,1.4201273918152,-98.691543579102),935,1497,403978,3767,
			vector():set(-144.297119140625,0.4970370024442673,-404.1590270996094),
			vector():set(0,0,0 ),"pripyat",0)
        level_map_spot(obj.id, "level_changer4", "В Восточную Припять")
        give_info("info_yan_pri1")
	end
end

function pri1_forest()
      -- создается переход с Восточной Припяти в Забытый Лес
	if (not has_info(	"info_pri1_forest" )) then
		local obj = create_lc(132000, vector():set(6.5819845199585,-0.50617444515228,431.99432373047),206177,3760,365107,2885,
			vector():set(222.00297546387,4.7978701591492,162.53837585449),
			vector():set(0,0,0 ),"puzir",0)
        level_map_spot(obj.id, "level_changer1", "В Забытый Лес")
		give_info("info_pri1_forest")
	end
end

function lab_under()
      -- создается переход с Х8 в Путепровод Припять-1.
	if (not has_info(	"info_lab_under" )) then
		local obj = create_lc(130022, vector():set(-86.088009887695,-36.53716307830811,81.4746684265137),2352,3844,1239,3772,
			vector():set(-46.7059990844727,8.31999969482422,455.630987792969),
			vector():set(0,0,0 ),"jupiter_underground",0)
        level_map_spot(obj.id, "level_changer3", "В Путепровод Припять-1")
        give_info("info_lab_under")
	end
end

function under_pri1()
      -- создается переход из Путепровода Припять-1 в Восточную Припять.
	if (not has_info(	"info_under_pri1" )) then
		local obj = create_lc(130023, vector():set(82.61710357666,28.351526260376,-222.54681396484),40755,3827,415475,3765,
			vector():set(185.36628723145,-0.50833475589752,-257.73150634766),
			vector():set(0,0,0 ),"pripyat",0)
        level_map_spot(obj.id, "level_changer1", "В Восточную Припять")
        give_info("info_under_pri1")
	end
end

function pri1_jup()
      -- создается переход с Восточной Припяти на Юпитер.
	if (not has_info(	"info_pri1_jup" )) then
		local obj = create_lc(130024, vector():set(311.923400878906,1.0266540527344,155.452056884766),403978,3767,14261,3700,
			vector():set(-423.471588134766,-2.11602973937988,-232.060592651367),
			vector():set(0,0,0 ),"jupiter",0)
        level_map_spot(obj.id, "level_changer2", "На Юпитер")
        give_info("info_pri1_jup")
	end
end

function jup_under()
      -- создается переход с Юпитера в Путепровод Припять-1.
	if (not has_info(	"info_jup_under" )) then
		local obj = create_lc(130025, vector():set(317.50564575195,13.820494651794,-330.11264038086),1222808,3745,1239,3772,
			vector():set(-46.7059990844727,8.31999969482422,455.630987792969),
			vector():set(0,0,0 ),"jupiter_underground",0)
        level_map_spot(obj.id, "level_changer3", "В Путепровод Припять-1")
        give_info("info_jup_under")
	end
end

function pri1_zaton()
      -- создается переход с Восточной Припяти на Затон.
	if (not has_info(	"info_pri1_zaton" )) then
		local obj = create_lc(130026, vector():set(181.64431762695,-0.506711602211,406.57440185547),411942,3769,274576,3665,
			vector():set(-339.29794311523,9.9404134750366,431.97296142578),
			vector():set(0,3.14,0 ),"zaton",0)
        give_info("info_pri1_zaton")
        level_map_spot(obj.id, "level_changer1", "На Затон")
	end
end

function sva_chaes2()
      -- создается переход со Свалки в Восточную Припять и другие переходы.
	local obj
	if (not has_info(	"info_sva_chaes2" )) then
		obj = create_lc(130027, vector():set(-309.81689453125,10.660300254822,-203.23162841797),38,260,434278,3765,
			vector():set(206.93473815918,-0.42643213272095,-265.46835327148),
			vector():set(0,0,0 ),"pripyat",0)
		level_map_spot(obj.id, "level_changer4", "В Восточную Припять")
		-- создается переход с Затона в Восточную Припять.
		obj = create_lc(130030, vector():set(-323.57330322266,19.470890045166,627.18048095703),303639,3665,414710,3769,
			vector():set(184.4153137207,-0.50399208068848,393.82348632813),
			vector():set(0,0,0 ),"pripyat",0)
        level_map_spot(obj.id, "level_changer1", "В Восточную Припять")
        give_info("info_sva_chaes2")
	end
end

function pri_pri1()
	local obj
		-- создается переход с Восточной Припяти в Центральную Припять.
		obj = create_lc(130028, vector():set(-231.28132629395,-1.2101984024048,31.831085205078),6811,3750,259152,2219,
			vector():set(188.64532470703,-2.1967782974243,227.76498413086),
			vector():set(0,0,0 ),"l11_pripyat",0)
        level_map_spot(obj.id, "level_changer4", "В Центральную Припять")
		-- создается переход с Центральной Припяти в Восточную Припять.
		obj = create_lc(130029, vector():set(189.59794616699,-2.1057658195496,232.89511108398),259791,2149,5587,3749,
			vector():set(-233.32069396973,-0.50898379087448,21.445573806763),
			vector():set(0,0,0 ),"pripyat",0)
        level_map_spot(obj.id, "level_changer2", "В Восточную Припять")
end

function zat_jup()
      -- создается переход с Затона на Юпитер.
	if (not has_info(	"info_zat_jup" )) then
		local obj = create_lc(130031, vector():set(-289.74868774414,40.953075408936,-477.16955566406),369405,3669,436258,3711,
			vector():set(-166.3133392334,-3.3640542030334,472.05075073242),
			vector():set(0,0,0 ),"jupiter",0)
        level_map_spot(obj.id, "level_changer3", "На Юпитер")
        give_info("info_zat_jup")
	end
end

function jup_zat()
      -- создается переход с Юпитера в Затон.
	if (not has_info(	"info_jup_zat" )) then
		local obj = create_lc(130032, vector():set(-167.93739318848,-1.4687540531158,484.27691650391),433738,3711,368170,3669,
			vector():set(-290.5163269043,41.015487670898,-468.53024291992),
			vector():set(0,0,0 ),"zaton",0)
        level_map_spot(obj.id, "level_changer1", "На Затон")
        give_info("info_jup_zat")
	end
end

function jup_pri()
	-- создается переход с Юпитера в Восточную Припять.
	if (not has_info(	"info_jup_pri" )) then
		local obj = create_lc(130033, vector():set(-436.270477,-1.556059,-265.591339),4661,3700,232248,3756,
			vector():set(304.50463867188,-0.50692754983902,160.43954467773),
			vector():set(0,0,0 ),"pripyat",0)
        level_map_spot(obj.id, "level_changer4", "В Восточную Припять")
        give_info("info_jup_pri")
	end
end

function lab_sar()
	local obj
		-- создается переход с Лабиринта в Саркофаг.
		obj = create_lc(130035, vector():set(-228.39886474609,17.315053939819,183.03189086914),99826,2950,7755,2417,
			vector():set(43.911926269531,49.282817840576,-31.283910751343),
			vector():set(0,0,0 ),"l12u_sarcofag",0)
        level_map_spot(obj.id, "level_changer2", "В Саркофаг")
end

function yan_aes1()
	local obj
		-- создается переход с Янтаря на ЧАЭС1.
		obj = create_lc(130036, vector():set(-24.512008666992,0.43465510010719,0.012824798002839),29988,1500,62534,2376,
			vector():set(119.96744537354,-0.10128895938396,-76.460708618164),
			vector():set(0,-1.57,0 ),"l12_stancia",0)
        level_map_spot(obj.id, "level_changer4", "На ЧАЭС-1")
end

function kor_bar_pri()
	local obj
		-- создается переход с Кордона в Бар.
		obj = create_lc(130037, vector():set(-214.75802001953,-22.829057693481,-161.16024475098),34720,47,41941,1230,
			vector():set(161.09335327148,-0.0012683868408203,44.192863464355),
			vector():set(0,0,0 ),"l05_bar",0,1.8,true)
		-- создается переход с Бара на Кордон.
		obj = create_lc(130038, vector():set(127.59644165039,-4.8250484466553,9.725421333313),35369,1238,34720,47,
			vector():set(-219.20263671875,-22.075307846069,-159.39805603027),
			vector():set(0,0,0 ),"l01_escape",0,1.8,true)
		-- создается переход с Бара в Центральную Припять.
		obj = create_lc(130039, vector():set(131.23512573242,-4.8305258750916,13.929775619507),35859,1238,23504,2151,
			vector():set(-105.2287902832,-0.57660186290741,259.98217773438),
			vector():set(0,0,0 ),"l11_pripyat",0,1.8,true)
		-- создается переход с Центральной Припяти в Бар.
		obj = create_lc(130040, vector():set(-108.4627532959,-0.087667495012283,272.69674072266),23517,2151,41941,1230,
			vector():set(161.09335327148,-0.0012683868408203,44.192863464355),
			vector():set(0,0,0 ),"l05_bar",0,1.8,true)
end

function create_sarkbunker_exit()
	-- создается переход c САРКОФАГА В ЛАБ Х-10
	if (not has_info(	"level_newtri" )) then
		local obj = create_lc(31410, vector():set(-13.26,47.71,46.57 ),200,2417,7698, 2773,
			vector():set(7.6585369,-23.5286808,17.2495479),
			vector():set(-0.00754,0,-0.999971508 ),"l10u_bunker",0)
		level_map_spot(obj.id, "level_changer3", "В Лабораторию Х-10")
        give_info("level_newtri")
	end
    -- создается переход из ЛАБ Х-10 в САРКОФАГ
	if (not has_info(	"level_newtwo" )) then
		local obj = create_lc(31510, vector():set(20.072347640991,-23.523380279541,15.896005630493),8597, 2773,414,2417,
			vector():set(-8.1581792831421,49.238555908203,44.329990386963),
			vector():set(0.0,0.0,-1.0 ),"l12u_sarcofag",0)
		level_map_spot(obj.id, "level_changer1", "to_sarcofag")
        give_info("level_newtwo")
	end
end

function create_sarchaes2_exit()
	-- создается переход c САРКОФАГА на ЧАЕС2
	if (not has_info(	"level_newfive" )) then
		local obj = create_lc(31610, vector():set(77.10116577,58.2671585,51.8668289),6406,2417,53648,  2537,
			vector():set(67.8906097,5.04050731,97.7711),
			vector():set(-0.8196038,0,0.57293063 ),"l12_stancia_2",0)
		level_map_spot(obj.id, "level_changer1", "to_stancia_2")
        give_info("level_newfive")
	end
    -- создается переход c ЧАЕС2 в САРКОФАГ
	if (not has_info(	"level_newfour" )) then
		local obj = create_lc(31710, vector():set(663.8462524,0.355151146,140.6202697),192695,2623,6406,2417,
			vector():set(77.10116577,58.2671585,51.8668289),
			vector():set(-0.997,0,0.06419),"l12u_sarcofag",0)
		level_map_spot(obj.id, "level_changer3", "to_sarcofag")
        give_info("level_newfour")
	end
end

-- Скриптовые переходы ОП-2.1
function darkscape_out()
	-- создается переход из Темной Лощины в Чернобыль-1.
	if (not has_info("info_darkscape_out" )) then
		local obj = create_lc(130041, vector():set(459.54,5.69,-533.63),967997,4609,112424,8992,
		vector():set(-261.46,-85.04,626.16),
		vector():set(0,0,0 ),"l57_outskirts",0)
        	level_map_spot(obj.id, "level_changer3", "to_chernobyl_1")
        	give_info("info_darkscape_out")
	end
end
function marsh_zavod()
	-- создается переход с Болот на Металлургический Завод.
	if (not has_info("info_marsh_zavod" )) then
		local obj = create_lc(130042, vector():set(57.59,10.64,530.33),169752,3484,200182,8300,
		vector():set(164.26,-2.04,217.77),
		vector():set(0,0,0 ),"l56_rostok_factory",0)
        	level_map_spot(obj.id, "level_changer4", "to_met_plant")
        	give_info("info_marsh_zavod")
	end
end
function zavod_marsh()
	-- создается переход с Металлургического Завода на Болота.
	if (not has_info("info_zavod_marsh" )) then
		local obj = create_lc(130043, vector():set(156.06,-2.77,221.36),193911,8304,173552,3484,
		vector():set(64.73,10.62,530.42),
		vector():set(0,0,0 ),"marsh",0)
        	level_map_spot(obj.id, "level_changer2", "to_swamp")
        	give_info("info_zavod_marsh")
	end
end

function military_forgotten()
	-- создается переход со Складов на Стройплощадку
	if not has_info("info_military_forgotten") then
		local obj = create_lc(130044, vector():set(145.21,-4.62,385.21),413942,1810,6213,9196,
		vector():set(-246.2,7.03,235.78),
		vector():set(0,0,0 ),"l58_forgotten",0)
        	level_map_spot(obj.id, "level_changer2", "to_construction_camp")
        	give_info("info_military_forgotten")
	end
end
function forgotten_military()
	-- создается переход со Стройплощадки на Склады
	if not has_info("info_forgotten_military") then
		local obj = create_lc(130045, vector():set(-252.03,6.86,235.72),3822,9196,412803,1812,
		vector():set(137.06,-3.09,400.73),
		vector():set(0,0,0 ),"l07_military",0)
        	level_map_spot(obj.id, "level_changer4", "to_military")
        	give_info("info_forgotten_military")
	end
end

function darkscape_darkvalley()
	-- создается переход из Тёмной Лощины в ТД.
	if (not has_info("info_darkscape_darkvalley" )) then
		local obj = create_lc(130046, 
		vector():set(-397.17758178711,1.3607201576233,638.25067138672),57679,4667,
		120811,815,vector():set(-45.26,0.43,-539.45),
		vector():set(0,0,0 ),"l04_darkvalley",0,3.5)
       	level_map_spot(obj.id, "level_changer4", "to_darkvalley")
		netpacket:modify(obj,"custom_data","[pt_move_if_reject]\npath = way_darkscape_reject_to_darkvalley")
       	give_info("info_darkscape_darkvalley")
	end
end

function darkscape_escape()
	-- создается переход из Тёмной Лощины на Кордон.
	if (not has_info("info_darkscape_escape" )) then
		local obj = create_lc(130047, 
		vector():set(-598.3466796875,-2.0202567577362,-407.19403076172),1371,4699,
		592029,0,vector():set(358.09,15.18,-35.86),
		vector():set(0,0,0 ),"l01_escape",0,3.5)
		netpacket:modify(obj,"custom_data","[pt_move_if_reject]\npath = way_darkscape_reject_to_escape")
        level_map_spot(obj.id, "level_changer3", "to_escape")
        give_info("info_darkscape_escape")
	end
end

function create_lc(story_id, pos, lv, gv, dlv, dgv, dpos, ddir, lvl_name, silent, radius, quiet)
	local obj = create_level_changer(story_id, pos, lv, gv, dlv, dgv, dpos, ddir, lvl_name, silent, radius)
	if not quiet then
		sms("create_lc_0", nil, nil, 10000)
	end
	return obj
end


