-- оптимизацыя LUA
-- https://ilovelua.wordpress.com/tag/%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F/
-- адаптацыя MMM_Corp, mmmsvit@gmail.com

local data = {
	values = {}
}

for i = 1, 10000 do
	table.insert(data.values, i)
end

local function simpleForTest()
	local t = profile_timer()
    t:start()
	
	local j
	for k = 1, 10000 do
		for i = 1, #data.values do
			j = data.values[i]
		end
	end

    t:stop()
 	log('~~~# end:     '..tostring(t:time()))
end

local function ipairsTest()
    local t = profile_timer()
    t:start()

	local j
	for k = 1, 10000 do
		for i, val in ipairs(data.values) do
			j = val
		end
	end
 
    t:stop()
	log('~~~ipairs end:'..tostring(t:time()))
end

function main()
for i = 1, 10 do
	simpleForTest()
	ipairsTest()
end

end

