--db.actor:set_actor_position(xyz(112.87,-1.94,1.6))

local obj = story_object(417)
if obj then
	log("! found [%s][%s]",obj:name(),tostring(obj.id))
	-- obj.direction=vector():set(0,0,0)
	-- if obj.online then
		-- ai:set_switch_online(obj.id, false)
		-- ai:set_switch_offline(obj.id, true)
		-- amk.convert_npc[obj.id] = 1 -- ставим в очередь на вывод в онлайн
	-- end

	release(obj)
	create(ai:spawn_id(obj.spawn_story_id))
end
--log("! create")
--alife():create("televizor_esc",xyz(-9.125937461853,5.8606271743774,-46.677627563477),162625,1043))
--[[
	snp.invul_on()
	give_info("vol_info_temp")
	give_info("sar_monolith_destroy")
	give_info("bar_deactivate_radar_done")
	give_info("arhara_shaxter_start")
	give_info("esc_serious_talk")
	give_info("dimak_doki_start")
	give_info("dar_door3_free")
	give_info("tutorial_end")
	got("teleportator",1)
	got("anom_egg",100)
	for	i=1, 65 do
		lost_all("arhara_obman"..tostring(i))
		give_info("arhara_obman"..tostring(i))
	end
	give_info("dimak_toolkit_done")
	give_info("fli_have_3")
	got("wpn_ognemet",1)
	got("wpn_gravigun",1)
	got("wpn_rg6_m2",1)
	got("wpn_kastet",1)
	got("ammo_vog-25he",5)
	got("ammo_vog-25fb",5)
	got("ammo_vog-25sg",5)
	got("ammo_vog-25sn",5)
	got("wpn_mp153",1)
	got("bioradar2",1)
	got("det_artefact_super",1)
	got("detector_elite_john",1)
	got("runner_tele",1)
	got("ammo_12x70_kart",30)
	got("ammo_balon",5)
	got("medkit",10)
	got("af_power_3",3)
	got("matras",1)
	got("kolbasa",10)
	got_money(4000000)	
--]]

--[[
	snp.invul_on()
	give_info("vol_info_temp")
	got("anom_egg",20)
	got("medkit",10)
	got("runner_tele",1)
	got("wpn_ks23",1)
	got("ammo_23x76_shrap",10)
	got("af_power_3",1)
	got_money(2000000)	
--]]

--	_G.death_manager = nil
--	buusty_dialog.voyaki_zasada_krot()
--	create("m_controller_normal",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
--	create("partizan_npc",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
--	local obj = create("yan_zombied_respawn_3",xyz(147.86102294922,-0.0037327408790588,59.646175384521),39663,1228)
--	create(3730)
--	snp_parad.parad_start()
--	sms(tostring(db.actor:object("bandit_veteran_outfit_m1") ~= nil))
--	akill.bottle_spawn()
--	sms(tostring(has_info("sahar_info_start")))
--	db.actor:drop_item(db.actor:active_item())
	
--	akill.weapon_mono_spawn()
--	timer("run", 2, "akill.hor_npc_dead2()")
--	disable_info("acv_zoolog")
--	give_info("esc_bridge_vodka_done")
--	give_info("doki_dimak_done")
--	disable_info("doki_dimak_done")
--	disable_info("sar_monolith_destroy")
--	give_info("flamethrower_quest_start")
--	give_info("sidorovich_daet_dobro")
--	give_info("bar_dolg_bunker_pass")
--	give_info("bar_dolg_community_leader")
--	give_info("bar_svoboda_rg6_done")
--	give_info("aes_zabor")
--	give_info("agroprom_military_case_done")
--	give_info("bar_darklab_document_done")
--	give_info("bar_deactivate_radar_done")
--	give_info("yan_kill_brain_done")
--	give_info("snp_parad_start")
--	give_info("dolgovazyi_voen2_done")
--	give_info("sidor_delo_done")
--	give_info("tel_dcity_kanaliy")
--	game.start_tutorial("dream_trailer12")

--	_G.Dream = nil _G.dream = nil _G.ui_matras = nil _G.Dream = dream.CDream()
--	_G.Treasure = nil _G.treasure = nil _G.Treasure = treasure.CTreasure()
--	_G.Inventory = nil _G.inventory = nil _G.Inventory = inventory.CInventory()

--	treasure.give()

--	release(server_object("__physic_destroyable_object_0019"))
--	create(10270)
--	_G.cycle_task = nil _G.Cycle_Task = nil	_G.Cycle_Task = cycle_task.CCycleTask()
--	_G.Cycle_Task:stats()
--	got("part_boar_leg",1)

--[[
	_G.lua_ext = nil
	prefetch("lua_ext")
	local xyzlg = string.explode("-247.08001708984,-8.905158996582,-72.884590148926,11439,66",",")
	log(xyzlg[1],xyzlg[2],xyzlg[3],xyzlg[4],xyzlg[5])
	local xyzlg = string.parse_nums("-247.08001708984,-8.905158996582,-72.884590148926,11439,66")
	log(xyzlg[1],xyzlg[2],xyzlg[3],xyzlg[4],xyzlg[5])
--]]

--	log(device().fov)
--	log(tostring(has_info("paused_on_load")))
--	log(""..xr_gulag.getGulagState(3070))
--	log(""..task_desc.name..task_desc.target..task_desc.target_count)
--	db.actor:set_actor_position(server_object("mil_dolg_stalker0006").position)
--	db.actor:set_character_rank(6000)

--	release(story_object(503))
--	create(ai:spawn_id(503))
--	release("pri_a28_physic_door_end_surge_room")
--	create(3078)
--	disable_info("sak_repair_box_done")
--	sms(tostring(has_info("sak_repair_box_done")), nil, nil, 10000)
--	relation_registry.change_community_goodwill("stalker", db.actor:id(), math.random(1,3))
--	sms(relation_registry.community_goodwill("stalker", db.actor:id()))
--	sms(tostring(db.actor.radiation), nil, nil, 10000)
--	db.actor:set_actor_direction(0)
--	lost("ballast")
--	got("wpn_ognemet",1)
--	got("ammo_balon",5)
--	got("part_psevdodog_tail",1)
--	got("part_carlic_hand",1)
--	got("af_mincer_meat",1)
--	got("repair_item_weapon",3)
--	got("repair_item_outfit",3)
--	got("vodka",10)
--	got("energy_drink",10)
--	got("kolbasa",10)
--	got("det_artefact_super",1)
--	got("bread",1)
--	db.actor:set_character_rank(6000)
--	got("hand_teleporter",1)
--	got("detektor_amorf",1)
--	got("wpn_spas23",1)
--	got("af_dummy_battery",1)
--	got("wpn_rpg7",1)
--	got("ammo_og-7b",15)
--	got("wpn_addon_scope_pgo_7v",1)
--	got("wpn_pmm",2)
--	got("vodka",5)
--	got("af_buliz",1)
--	got("amk_transmutator",1)
--	got("wpn_p90",1)
--	got_money(100000)
--	got("part_burer_hand",1)
--	got("wpn_gravigun",1)
--	got("wpn_svd_m3",1)
--	got("bioradar2",1)
--	got("wpn_gravigun",1)
--	lost("teleportator")
--	snp.invul_off()
--	snp.invul_on() got("anom_egg",3) give_info("vol_info_temp")
--	db.actor:kill(db.actor)
--	news_manager.send_tip(tostring(has_good("wpn_ak74",3)), nil, nil, 10000)
--	lost_good("wpn_ak74",3)
--	smart_terrain.stat()
--	got_treasure("atp_arhara_secret_3")
--	_G.Treasure:check()
--	arhara_dialog.delete_dt_zone_zvuk()
--	sms(server_object("cave_scelety_zastenoi").id)
--	level.set_weather("grey",true)

--[[ Спавн изношенного оружия
	local obj
	for i=1,1 do
		obj = create("wpn_knife", db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		level.client_spawn_manager():add(obj.id, 0, 
			function (cond, id, obj)
				level_object(id):set_condition(cond)
			end
		, math.random()+0.3)
	end
--]]


--[-[ -- поиск объекта
--	local obj
--	local actor_level = object_level(db.actor)
--	local cnt=0
--	for i=1,65534 do
--		obj = server_object(i)
--		if obj then
--		obj = level_object(i)
--		if obj then
--		if obj and obj:clsid() == clsid.inventory_box then
--		if obj and obj:clsid() == clsid.level_changer then
--		if obj and obj:clsid() == clsid.smart_terrain then
--		if obj and IAmAStalker[obj:clsid()] and not string.find(obj:name(), "bar_ecolog_crush_") then
--		if obj and obj:name() == "cave_scelety_zastenoi" then
--		if obj and string.find(obj:name(), "mil_killer_respawn_3") then
--		if obj and obj.id == 34392 then
--		if obj and string.find(obj:name(), "mar_holod_priemnik") then
--		if obj and string.find(obj:name(), "fracture_normal23458") and object_level(obj) == actor_level then
--		if obj and boxes[obj.parent_id] then
--		if obj and string.find(obj:name(),"af_") and obj:parent() == nil 
--			and object_level(obj) == actor_level
--		then
--		if obj and obj.parent_id ~= 0 and db.actor:position():distance_to(obj.position) < 3 then
--		if obj and IAmAStalker[obj:clsid()] and object_level(obj) == actor_level then
--		if obj and IAmAStalker[obj:clsid()] and obj.online then
--		if obj and IAmAStalker[obj:clsid()] and obj:smart_terrain_id() ~= 65535 and server_object(obj:smart_terrain_id()):name() == "esc_blokpost" then
--		if obj and obj.smart_terrain_id and obj:smart_terrain_id() == 35182 then
--		if obj and (IAmAStalker[obj:clsid()] or IAmAMonster[obj:clsid()]) then
--			map_spot(obj.id, "blue_location", obj:name())
--			release(obj)
--			db.actor:set_actor_position(obj.position)
--			local txt = tostring(IAmAStalker[obj:clsid()])
--			sms(txt, nil, nil, 10000)
--[=[
			local params = netpacket:get(obj)
			log(obj.id, tostring(object_level_name(obj)), params.dest_level_name)
			if obj.m_story_id then
				log("m_story_id ", obj.m_story_id)
			end
--]=]
--[=[			local params = netpacket:get(obj)
			local gp = graph:vertex(obj.m_game_vertex_id):level_point()
			log(obj:name(), obj:section_name(), obj:clsid(), obj.position.x, obj.position.y, obj.position.z, obj.m_level_vertex_id, obj.m_game_vertex_id, params.visual_name, "["..params.custom_data:getString().."]", gp.x, gp.y, gp.z)
--]=]
--			cnt=cnt+1
--			log("name: ".. tostring(obj:name()))
--			log("item: ".. obj:section_name().." parent: "..obj.parent_id)
--			log("item: ".. obj:section().." y: "..obj:position().y)
--			log("spot: ".. tostring(has_map_spot(obj:id(), "level_changer")))
--			obj:clear_smart_terrain()
--[=[
			log("name: ".. tostring(obj:name()))
			log("online: ".. tostring(obj.online))
			log("level: ".. tostring(object_level_name(obj)))
			local params = netpacket:get(obj)
			log(params.custom_data:getString())
			log("smart_terrain_id: ".. tostring(obj:smart_terrain_id()))
--			log("smart_terrain: ".. tostring(server_object(obj:smart_terrain_id()):clsid()==clsid.smart_terrain))
			if obj:smart_terrain_id() ~= 65535 then
				log("smart_terrain_name: ".. server_object(obj:smart_terrain_id()):name())
			end
--]=]
--			break
--		end
--	end
--	log("cnt: "..cnt)
--]]

--[[ очистка всех монстров\сталкеров в офлайне
	local obj
	for i=1,65534 do
		obj = server_object(i)
--		obj = level_object(i)
--		if obj and IAmAMonster[obj:clsid()] and obj:section() ~= "boar_child" and obj:section() ~= "boar_mother" and obj:section() ~= "boar_children" then
			if obj and (IAmAMonster[obj:clsid()] or IAmAStalker[obj:clsid()]) then
--			if obj and IAmAMonster[obj:clsid()] then
--			if obj and IAmAStalker[obj:clsid()] then
--			if obj and obj:section() == "snp_kordon1" and obj:alive() then
--			obj:kill(db.actor)
			release(server_object(i))
		end
	end
--]]

--[[
	local v1,v2 = 26427, 26493
	local obj
	if not prev_art then
		prev_art = v1
		for i = 800001,804740 do
			release(story_object(i))
		end
	end
	if prev_art <= v2 then
		obj = create(prev_art)
		log(prev_art.." "..obj:name())
		release(obj:name())
		obj = create(prev_art)
		db.actor:set_actor_position(obj.position)
		release(obj)
		prev_art = prev_art+1
	end
--]]

--[[
--snp.release_all_online("vehicle_btr")
--create_car("vehicle_btr",xyz(255.91418457031,5.349621295929,21.442276000977),1404424,3684, "scripts\\technics\\volna_btr.ltx")
--]]

--[-[ ускорение времени
	-- if tf then
		-- level.set_time_factor(config:r_float("alife","time_factor")*1000)
		-- tf = false
	-- else
		-- level.set_time_factor(config:r_float("alife","time_factor"))
		-- tf = true
	-- end
--]]

--[[ тест позиции
	if prev_art then
		release(prev_art)
		prev_art = nil
	end
	if prev_art2 then
		release(prev_art2)
		prev_art2 = nil
	end

--[-=[
	local b = {
	{position={x=-49.587427520752,y=10.0211449813843,z=187.45875549316},gv=2521,lv=7877}
	} local a = b[1] 
	
	if a then
		prev_art = create("val_taynik_36", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
	else
		--prev_art = create("koster", xyz(32.0455589294434,15.798966217041,664.038208007813), 313133, 207)
	end

--	db.actor:set_actor_position(xyz(a.position.x,a.position.y,a.position.z))
--]=]

--	prev_art = amk_anoms.spawn_rand_anom(vector():set(110.00815582275,0.8815416097641,350.41976928711),234,411827)
--	sms(prev_art:section_name(), nil, nil, 5000)
--	prev_art = create("car7",xyz(476.4153137207,27.045625686646,-444.02090454102),1467869,3745)
--	prev_art = create("trofim_npc",xyz(82.861618041992,0.054342240095139,-9.3183221817017),275941,989)

--]]
	
--[[ хит актору
	sms(tostring(db.actor.health), nil, nil, 10000)
	local h = hit()
	h.draftsman = db.actor
	h.type = hit.fire_wound
	h.direction = db.actor:position()
	h:bone("bip01_spine")
	h.power = 1
	h.impulse = 10
	db.actor:hit(h)
	sms(tostring(db.actor.health), nil, nil, 10000)
--]]

--[[ переспавн объекта из алспаун
	local obj = server_object("trader_door")
	if obj then
--		log("id: "..tostring(obj.id))
--		log("logic: "..tostring(obj:spawn_ini():section_exist("logic")))
--		log("scheme: "..tostring(db.storage[obj.id]))
		release(obj)
--		ai:set_switch_online(obj.id, true)
--		ai:set_switch_offline(obj.id, true)
	end
	create(3048)
--		ai:set_switch_online(obj.id, true)
--		ai:set_switch_offline(obj.id, true)
--]]

--[[ отношения в Волне
	local obj2 = level_object(server_object("buusty_zaton").id)
	local obj1 = snp.object_by_section("proper70_zaton")
--	obj1:set_goodwill(100,obj2)
	sms(tostring(obj1:goodwill(obj2)), nil, nil, 10000)
--]]

--[[ Письма тест
	for i = 1,44 do
		give_info(("letter_"..i))
	end
--]]

--[[ тест новостей
local news_uniq={
--"Мародёры зажали, выручайте!\\n%c[sender]Потап\\n%c[default]Координаты-то приложи, умник.",

}
for i=1,#news_uniq do
	local uniq=news_uniq[i]
	local name,sname = amk_mod.get_news_sender()
	amk.send_tip(uniq,name.." "..sname,nil,30,"uniq")
end
--]]

--	_G.news_manager = nil
--[=[
local mod_news={
--"%c[sender]Витязь\\n%c[default]Коршун, я Витязь. Как слышишь? Прием.\\n%c[sender]Коршун\\n%c[default]Витязь, я Коршун. Стоим у объекта. Какие-то странные помехи. Аппаратура полностью вышла из строя. Полчаса назад отбили нападение монстров. Совсем неизвестных монстров и... Остальное потом. Есть потери. Запрашиваю срочную эвакуацию. Прием...",

}
for i=1,#mod_news do
	local mod_news = mod_news[i]
	-- попробуем подобрать иконку
	local x,y, pos
	pos = string.find(mod_news,"[default]",1,true)
	if pos then
		x,y = news_manager.get_sender_icon(string.sub(mod_news,1,pos-5)..":")
	else
		x,y = 498,47
	end

	db.actor:give_game_news(mod_news, "ui\\ui_iconsTotal", Frect():set(x,y,83,47), 0, string.len(mod_news)/8*1000)
	say([[device\pda\pda_tip]])
end
--]=]

--[[Отладка zonedocs
		local se_obj = create("zone_docs",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
		if     has("zone_docs",3) then
			give_info("voronin_docs1_have")
		elseif has("zone_docs",1) then
			give_info("voronin_docs1_almost_have")
		end
--]]
--		local se_obj = create("zone_docs",xyz(-97.878524780273,15.606694221497,127.96105957031),109975,2881)

--[=[
	local p = "upd.w"
	local t = {}
	t.upd = {}
	if string.find(p,".") then
		local i = p:explode(".")
		t[i[1]][i[2]] = 1
	else
		t[p] = 1
	end
	t[p] = 1
	sms(t.upd.w)
--]=]

--	local obj = create("bibliotekar",xyz(-52.541351318359,2.2499685287476,102.57232666016),176274,9180)
--	netpacket:modify(obj, "visual_name", "monsters\\bibliotekar\\bibliotekar_black", "story_id", 1990026)

--[[ Спавн раненого
		local obj = create("atp_brigada_respawn_3",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
--		local obj = create("gar_bandit_respawn_1",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())

		netpacket:modify(obj, "health", 0.1, "upd.health", 0.05)
		got("medkit",1)
--]]
		
--[[	спавн летающего острова
	__y1 = 17
	
	if not __y2 then
		__y2 = 0
	end

--	__lv = db.actor:level_vertex_id() __gv = db.actor:game_vertex_id() __pos = db.actor:position() __y2 = 0
	__pos = vector():set(__pos.x,__pos.y+__y1-__y2,__pos.z)
	__y2 = __y1
	log("fli:") log("{position={x="..__pos.x..",y="..__pos.y..",z="..__pos.z.."},gv="..__gv..",lv="..__lv.."},") log("vector():set("..__pos.x..","..__pos.y..","..__pos.z.."),"..__lv..","..__gv..")")
--
	if prev_art then
		release(prev_art)
	end
	if prev_art2 then
		release(prev_art2)
	end

	prev_art = create("fly_island",__pos,__lv,__gv)
	netpacket:modify(prev_art, 
		"object_flags", -198,		-- 0xffffff3a object_flags
		"visual_flags", 1,			-- 0x1 visual_flags
		"skeleton_name", "idle",
		"skeleton_flags", 1,
		"physic_type", 3,			-- 0x3
		"mass", 100,
		"fixed_bones", "link")
	prev_art2 = create("zone_fly_island",__pos,__lv,__gv)
]]

--[[ респавн островов
	local obj, section
	for i=1,65534 do
		obj = server_object(i)
		if obj then
			section = obj:section_name()
			
			if (section == "fly_island" or section == "zone_fly_island" or section == "zone_tuman3") then
--			if string.find(section,"fenrir_jupiter") then
				release(obj, true)
			end
		end
	end

	fly_island.create_fly_island(xyz(-246.46073913574,3.1428375244141,-21.434331893921),9980,67)
]]

--[[ Туман над болотами
	if prev_art3 then
		release(prev_art3)
	end
	prev_art3 = create("zone_tuman3",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
]]
