--[[
Универсальный скрипт больших битв с монстрами/неписями
Поддерживаются:
Спавн по таймеру каждой волны монстров
Передышки между волнами
Спавн неподалеку от гг рюкзака с патронами/аптечками по время передышки с выдачей информации через СМС
Монстры спавнятся не вокруг ГГ, а в определенном секторе справа, слева или сзади ГГ рандомно, на указанном удалении. Спереди не спавнятся.
"Быстрый" уборщик, который во избежание тормозов убирает скопления трупов монстров при удалении гг от них на определенное расстояние

начало битвы запускается так: 
timer("battle", 0, {"level", num, 1})
где
level - уровень, на котором битва;
num - номер битвы на уровне;
1 - начинаем с первой волны

Замечания:
Вместо монстров можно прописывать секции неписей (монолита, например). Только уборщик не будет убирать их трупы.
Если в одной из волн прописать секции дружественных неписей - то они также заспавнятся и будут воевать на стороне гг.
]]

local cleanup_distance = 50				-- расстояние от ГГ в м, на котором уборщик убирает трупы
local rest_timeout = 120				-- время передышки в секундах (добавляется ко времени следущей волны +-20%)
local min_good_distance = 40			-- минимальная дистанция, на которой можно спавнить волну. если подходящий вертекс на указанном расстоянии или дальше не находится (гг заныкался в закутке - не находится в открытом месте) то спавн волны откладывается
local min_good_distance_timeout = 10	-- время в реальных с, на которое откладывается спавн след волны, если гг заныкался

local monster_cnt = 0					-- общее количество заспавненных монстров с момента последней передышки

-- лекарства для рюкзака
local medkits = {"medkit", "medkit_army", "medkit_scientic", "bandage"}

-- таблица настроек битв
-- Оптимизаторам: про цифры в квадратных скобках я знаю, что они лишние - написал специально, чтобы было понятнее - не убирать!
local battles = {
	marsh = {							-- территория

	--[=[ Типичный пример настройки битвы на Болотах, где используются все параметры - можно раскомментить и попробовать, будет работать)
		[1] = {							-- номер битвы на территории (для нескольких битв)
			[1]	= {						-- номер волны монстров
				dist = 70,				-- расстояние от ГГ в метрах. не задавать меньше min_good_distance
				timeout = 30,			-- время до следующей волны в секундах (радномно выбирается в интервале +-20%)
				enemy = {				-- сколько и каких монстров/неписей в волне
					["bloodsucker_normal_horror"] = 1,	-- секция, количество
					["fracture_normal_horror"] = 2,
					["dog_normal_horror"] = 2
				}
			},
			[2]	= {
				dist = 50,
				timeout = 20,
				enemy = {
					["fracture_strong_horror"] = 2,
					["zombie_immortal_horror"] = 2,
					["zombie_hell_horror"] = 2
				},
				rest = true,			-- если задано - передышка, ко времени след волны добавляется время передышки
				rukzak = true,			-- если задано - спавним тайник. должен обязательно быть задан rest иначе не сработает
				ruk_sms = 					-- если задано - после спавна рюкзака выдается смс с указанным текстом
					"%c[sender]АРИАДНА:\\n%c[sms_red]Вроде затихло. Где-то неподалеку должен быть резервный тайник с патронами и аптечками. Поищи его, пока затишье!",
				ruk_snd = [[sms\ariadna\ariadna_1]]	-- если задано - озвучка СМС выше
				medkit = 5,				-- если задано - количество аптечек или бинтов в тайнике (рандом от 0 до указанного)
				ammo = 1/2,				-- если задано - количество пачек патронов для оружия в активных слотах по отношению к общему количеству заспавненных монстров с момента последней передышки
				podstvol = 1/3,			-- если задано - количество снарядов для подствольника (если он есть в активных слотах) по отношению к общему количеству заспавненных монстров с момента последней передышки
				items = {				-- если задано, спавним эти предметы
					["grenade_f1_double"] = 2,		-- секция, количество
					["grenade_f1"] = 3,
					["grenade_rgd5"] = 1
				}
			},
			[3]	= {
				dist = 20,
				timeout = 30,
				enemy = {
					["bloodsucker_normal_horror"] = 1,
					["fracture_normal_horror"] = 2,
					["dog_normal_horror"] = 2,
					["peshera_xabaruch"] = 1,			-- здесь для примера прописаны друзья из пещеры)
					["peshera_stahanov"] = 1
				}
			},
			[4]	= {
				dist = 30,
				timeout = 10,			
				enemy = {
					["fracture_strong_horror"] = 2,
					["zombie_immortal_horror"] = 2,
					["zombie_hell_horror"] = 2
				}
			},
			[5]	= {
				info = "info_artmod_globus",			-- если задано - выдается этот поршень
				func = "kostya_dialog.give_ammo(2)",	-- если задано - выполняется эта функция с указанными параметрами
				tip = "Битва закончена"					-- если задано - выдается это сообщение
				tip_snd = [[sms\battle\final]]			-- если задано - озвучка СМС выше
				-- Эти параметры можно задавать в любой волне. Если написать так, как написано здесь - то эта последняя, завершающая волна не выполнит никакого спавна, а просто через время, указанное в предыдущей волне, выдастся финальный поршень и выполнится финальная функция.
			}
		},
]=]
		[2] = {
			[1] = {
                dist = 70,
                timeout = 150,
                enemy = {
					["fracture_strong"] = 1,
					["zombie_trup2"] = 1,
					["tushkano_normal"] = 3,
					["tushkano_strong"] = 3,
					["winger"] = 5,
					["zombie_hell8"] = 1
				}
			},
			[2]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 3,
					["boar_kachok"] = 1,
					["flesh_swamp"] = 1,
					["stinger"] = 5,
					["flesh_strong"] = 1
				}
			},
			[3]	= {
				dist = 70,
				enemy = {
					["zombie_babka_weak"] = 2,
					["zombie_babka_normal"] = 2,
 					["zombie_babka_strong"] = 2,
                   			["gigant_virus_strong"] = 1,
					["tushkano_normal"] = 3,
					["tushkano_strong"] = 3,
					["winger"] = 4,
					["stinger"] = 4,
 					["zombie_hell3"] = 1,
 					["zombie_hell4"] = 1,
 					["zombie_hell5"] = 1,
 					["zombie_hell6"] = 1,
 					["zombie_hell2"] = 1
				}
			}
		},
-- Akill begin
-- Охота на библиотекарей
		[31] = {
			[1]	= {
				timeout = 180
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_dyak")..":\\n%c[sms_red]"..translate("battle_boloto_31_2_0"),
				tip_snd = [[sms\diak\battle_boloto_31_2]],
			},
			[3]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["bibliotekar"] = 4
				}
			},
			[4]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 1
				},
				tip = "%c[sender]"..translate("name_dyak")..":\\n%c[sms_red]"..translate("battle_boloto_31_4_0"),
				tip_snd = [[sms\diak\battle_boloto_31_4]],
			},
			[5]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 1
				},
				tip = "%c[sender]"..translate("name_dyak")..":\\n%c[sms_red]"..translate("battle_boloto_31_5_0"),
				tip_snd = [[sms\diak\battle_boloto_31_5]],
			},
			[6]	= {
				dist = 90,
				enemy = {
					["bibliotekar"] = 1,
					["ohota_biblik1"] = 1,
					["ohota_biblik2"] = 1
				}
			}
		},
-- Ловец мутантов
		[33] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_arni")..":\\n%c[sms_red]"..translate("battle_33_2_0"),
				tip_snd = [[sms\arni\battle_33_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_33_3_0"),
				tip_snd = [[sms\strelok\battle_33_3]],
			},
			[4]	= {
				tip = "%c[sender]"..translate("name_arni")..":\\n%c[sms_red]"..translate("battle_33_4_0"),
				tip_snd = [[sms\arni\battle_33_4]],
			}
		},
-- Незваные гости
		[34] = {
			[1]	= {
				timeout = 10
			},
			[2]	= {
				timeout = 60,
				tip = "%c[sender]"..translate("name_sviblov")..":\\n%c[sms_red]"..translate("sms_battle_0_0")
			},
			[3]	= {
				timeout = 100,
				func = "akill.volna_reid_spawn()"
			},
			[4]	= {
				func = "akill.volna_reid_desant()"
			}
		},
		[35] = {
			[1]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_boloto_35_1_0"),
				tip_snd = [[sms\net\battle_boloto_35_1]],
			},
			[2]	= {
				timeout = 60,
				tip = "%c[sender]"..translate("name_sviblov")..":\\n%c[sms_red]"..translate("sms_battle_1_0")
			},
			[3]	= {
				func = "akill.volna_reid_heli()"
			}
		},
-- Сбежавшие, Хорь
		[36] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("sms_battle_2_0"),
				func = "akill.hor_mistery1()"
			},
			[3]	= {
				timeout = 15,
				func = "akill.hor_mistery2()"
			},
			[4]	= {
				func = "akill.hor_mistery3()"
			}
		},
-- В обличье зверя
		[37] = {
			[1]	= {
				timeout = 6
			},
			[2]	= {
				timeout = 5,
				func = "akill.venom_dream_drink()"
			},
			[3]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("sms_battle_3_0")
			},
			[4]	= {
				timeout = 12,
				func = "akill.venom_dream_effect()"
			},
			[5]	= {
				info = "venom_dream_spawn"
			}
		}
	},
-- Охота на псевдособак
	l02_garbage = {	
		[30] = {
			[1]	= {
				timeout = 60
			},
			[2]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["pseudodog_strong"] = 5,
					["dog_normal"] = 5,
					["dog_zombie"] = 1,
					["dog_strong"] = 7
		 		}
			},
			[3]	= {
				dist = 50,
				enemy = {
					["ohota_dog1"] = 1,
					["ohota_dog2"] = 1,
					["dog_strong"] = 10
				}
			}
		},
-- Чужой среди своих, разговор с Прапором
		[32] = {
			[1]	= {
				timeout = 25
			},
			[2]	= {
				dist = 60,
				timeout = 30,
				enemy = {
					["dog_habaruch"] = 3,
					["dog_skeleton"] = 5,
					["dog_strong"] = 4,
					["dog_zombie"] = 1,
					["pseudodog_big"] = 1,
					["pseudodog_strong"] = 2
		 		}
			},
			[3]	= {
				tip = "%c[sender]"..translate("name_grach")..":\\n%c[sms_red]"..translate("battle_garbage_32_3_0"),
				tip_snd = [[sms\grach\battle_garbage_32_3]],
				timeout = 30,
				dist = 60,
				enemy = {
					["boar_strong"] = 4,
					["molerat"] = 4,
					["kikimora"] = 4,
					["stinger"] = 5,
					["volkodav"] = 1
				}
			},
			[4]	= {
				func = "akill.borov_peremirie()"
			}
		}
	},
-- Резервный схрон
	l11_pripyat = {
		[31] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				func = "akill.golem_npc_spawn()",
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("golem_npc_spawn_0"),
				tip_snd = [[sms\net\golem_npc_spawn]]    			
			}
		},
-- Тайник Ноя
		[32] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 70,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_pripyat_32_2_0"),
				tip_snd = [[sms\strelok\battle_pripyat_32_2]],
			},
			[3]	= {
				timeout = 30,
				func = "akill.noi_teleport2_tp()"
			},
			[4]	= {
				timeout = 3,
				func = "akill.noi_teleport3_tp()"
			},
			[5]	= {
				timeout = 70,
				info = "volna_sak_test",
				func = "akill.sak_zvuk()"
			},
			[6]	= {
				timeout = 2,
				func = "akill.noi_teleport_end()"
			},
			[7]	= {
				timeout = 7,
				func = "akill.sak_effect()"
			},
			[8]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_pripyat_32_8_0"),
				tip_snd = [[sms\strelok\battle_pripyat_32_8]],
			},
			[9]	= {
				timeout = 25,
				func = "akill.taynik_noi_have()"
			},
			[10]	= {
				timeout = 17,
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("battle_pripyat_32_10_0"),
				tip_snd = [[sms\noy\battle_pripyat_32_10]],
			},
			[11]	= {
				timeout = 17,
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("battle_pripyat_32_11_0"),
				tip_snd = [[sms\noy\battle_pripyat_32_11]],
			},
			[12]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_operator_svyazi")..":\\n%c[sms_red]"..translate("battle_pripyat_32_12_0"),
				tip_snd = [[sms\net\battle_pripyat_32_12]],
				},
			[13]	= {
				timeout = 10,
				func = "akill.taynik_noi_done()"
			},
			[14]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_obschaya_set")..":\\n%c[sms_red]"..translate("battle_pripyat_32_14_0"),
				tip_snd = [[sms\net\battle_pripyat_32_14]],
			},
			[15]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_obschaya_set")..":\\n%c[sms_red]"..translate("battle_pripyat_32_15_0"),
				tip_snd = [[sms\net\battle_pripyat_32_15]],
			},
			[16]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_obschaya_set")..":\\n%c[sms_red]"..translate("battle_pripyat_32_16_0"),
				tip_snd = [[sms\net\battle_pripyat_32_16]],
				},
			[17]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_obschaya_set")..":\\n%c[sms_red]"..translate("battle_pripyat_32_17_0"),
				tip_snd = [[sms\net\battle_pripyat_32_17]],
			},
			[18]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_obschaya_set")..":\\n%c[sms_red]"..translate("battle_pripyat_32_18_0"),
				tip_snd = [[sms\net\battle_pripyat_32_18]],
				},
			[19]	= {
				tip = "%c[sender]"..translate("name_obschaya_set")..":\\n%c[sms_red]"..translate("sms_battle_4_0")
			}
		},
-- Засада BW в Припяти
		[33] = {
			[1]	= {
				timeout = 4
			},
			[2]	= {
				timeout = 2,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_pripyat_33_2_0"),
				tip_snd = [[sms\net\battle_pripyat_33_2]],
			},
			[3]	= {
				timeout = 2,
				func = "akill.zasada_bw_shoot()"
			},
			[4]	= {
				timeout = 1,
				func = "akill.zasada_bw_shoot_mimo()"
			},
			[5]	= {
				timeout = 2,
				func = "akill.zasada_bw_shoot_mimo()"
			},
			[6]	= {
				timeout = 2,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_pripyat_33_6_0"),
				tip_snd = [[sms\net\battle_pripyat_33_6]],
			},
			[7]	= {
				func = "akill.zasada_bw_spawn()"
			}
		}
	},
-- Фото Гаусс-установки
	l05_bar = {
		[30] = {
			[1]	= {
				timeout = 25
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_hrebet")..":\\n%c[sms_red]"..translate("battle_bar_30_2_0"),
				tip_snd = [[sms\hrebet\battle_bar_30_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_bar_30_3_0"),
				tip_snd = [[sms\strelok\battle_bar_30_3]],
			},
			[4]	= {
				timeout = 25,
				tip = "%c[sender]"..translate("name_hrebet")..":\\n%c[sms_red]"..translate("battle_bar_30_4_0"),
				tip_snd = [[sms\hrebet\battle_bar_30_4]], 
			},
			[5]	= {
				info = "volna_foto_start"
			}
		},
-- Отдали снимки Гаусс-установки
		[31] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_hrebet")..":\\n%c[sms_red]"..translate("battle_bar_31_2_0"),
				tip_snd = [[sms\hrebet\battle_bar_31_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_bar_31_3_0"),
				tip_snd = [[sms\strelok\battle_bar_31_3]],
			},
			[4]	= {
				tip = "%c[sender]"..translate("name_hrebet")..":\\n%c[sms_red]"..translate("battle_bar_31_4_0"),
				tip_snd = [[sms\hrebet\battle_bar_31_4]],
			}
		},
-- Окончание расследования убийства
		[33] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 17,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_bar_33_2_0"),
				tip_snd = [[sms\strelok\battle_bar_33_2]],
			},
			[3]	= {
				timeout = 13,
				tip = "%c[sender]"..translate("name_voronin")..":\\n%c[sms_red]"..translate("battle_bar_33_3_0"),
				tip_snd = [[sms\voronin\battle_bar_33_3]],
			},
			[4]	= {
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_bar_33_4_0"),
				tip_snd = [[sms\strelok\battle_bar_33_4]],
			}
		},
-- Опасные связи
		[35] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_sms()"
			},
			[3]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_zvuk()"
			},
			[4]	= {
				timeout = 15,
				func = "akill.kontrik_vodka_start()"
			},
			[5]	= {
				timeout = 6,
				info = "kontrik_vodka_start"
			},
			[6]	= {
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_bar_35_6_0"),
				tip_snd = [[sms\strelok\battle_bar_35_6]],
			}
		},
-- Опасные связи, продолжение
		[36] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_sms2()"
			},
			[3]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_zvuk()"
			},
			[4]	= {
				timeout = 17,
				func = "akill.kontrik_vodka_start()"
			},
			[5]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("sms_battle_5_0")
			},
			[6]	= {
				func = "akill.kontrik_vodka_have()"
			}
		}
	},
-- После рейда бандитов
	l04_darkvalley = {
		[30] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				timeout = 18,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_darkvalley_30_2_0"),
				tip_snd = [[sms\strelok\battle_darkvalley_30_2]],
			},
			[3]	= {
				tip = "%c[sender]"..translate("name_skitalets")..":\\n%c[sms_red]"..translate("battle_darkvalley_30_3_0"),
				tip_snd = [[sms\skitalec\battle_darkvalley_30_3]],
			}
		},
-- Помутнение
		[31] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 2,
				func = "akill.kontrik_zasada_soldier()"
			},
			[3]	= {
				timeout = 4,
				func = "akill.kontrik_vodka_zvuk()"
			},
			[4]	= {
				func = "akill.kontrik_zasada_zombied()",
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_darkvalley_31_4_0"),
				tip_snd = [[sms\strelok\battle_darkvalley_31_4]],
			}
		},
-- Ночной дозор, комплекс
		[32] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_darkvalley_32_2_0"),
				tip_snd = [[sms\net\battle_darkvalley_32_2]],
				func = "akill.night_watch_komplex_polter()"
			},
			[3]	= {
				timeout = 90,
				func = "akill.night_watch_komplex_polter()"
			},
			[4]	= {
				func = "akill.night_watch_borov_polter1()"
			}
		},
-- Ночной дозор, заправка
		[33] = {
			[1]	= {
				timeout = 2
			},
			[2]	= {
				timeout = 50,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_darkvalley_33_2_0"),
				tip_snd = [[sms\net\battle_darkvalley_33_2]],
			},
			[3]	= {
				func = "akill.night_watch_borov_polter2()"
			}
		},
-- Ночной дозор, база бандитов
		[34] = {
			[1]	= {
				timeout = 4
			},
			[2]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_darkvalley_34_2_0"),
				tip_snd = [[sms\net\battle_darkvalley_34_2]],
				func = "akill.night_watch_baza_polter()"
			},
			[3]	= {
				timeout = 120,
				func = "akill.night_watch_baza_polter()"
			},
			[4]	= {
				func = "akill.night_watch_borov_polter3()"
			}
		},
-- Телохранитель
		[35] = {
			[1]	= {
				timeout = 15
			},
			[2]	= {
				timeout = 15,
				func = "akill.trofim_song()"
			},
			[3]	= {
				timeout = 30,
				dist = 41,
				enemy = {
					["molerat"] = 2
				}
			},
			[4]	= {
				timeout = 35,
				dist = 41,
				enemy = {
					["molerat"] = 2
				}
			},
			[5]	= {
				timeout = 35,
				dist = 41,
				enemy = {
					["boar_strong"] = 3
				}
			},
			[6]	= {
				timeout = 35,
				dist = 41,
				enemy = {
					["pseudodog_strong"] = 3
				}
			},
			[7]	= {
				timeout = 40,
				dist = 41,
				enemy = {
					["boar_kachok"] = 1
				}
			},
			[8]	= {
				dist = 41,
				enemy = {
					["volkodav"] = 2
				}
			}
		}
	},
-- Преследуем вояк с журналом полётов
	l03u_agr_underground = {
		[30] = {
			[1]	= {
				timeout = 8
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agr_underground_30_2_0"),
				tip_snd = [[sms\strelok\battle_agr_underground_30_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agr_underground_30_3_0"),
				tip_snd = [[sms\strelok\battle_agr_underground_30_3]],
			},
			[4]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_adrenalin")..":\\n%c[sms_red]"..translate("battle_agr_underground_30_4_0"),
				tip_snd = [[sms\adrenalin\battle_agr_underground_30_4]],
			},
			[5]	= {
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agr_underground_30_5_0"),
				tip_snd = [[sms\strelok\battle_agr_underground_30_5]],
			}
		}
	},
-- Охотник и добыча
	puzir = {
		[30] = {
			[1]	= {
				timeout = 13
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_puzir_30_2_0"),
				tip_snd = [[sms\strelok\battle_puzir_30_2]],
			},
			[3]	= {
				timeout = 7,
				func = "akill.predator_vizor()"
			},
			[4]	= {
				timeout = 2,
				func = "akill.predator_target()"
			},
			[5]	= {
				timeout = 5,
				func = "akill.predator_hit()"
			},
			[6]	= {
				timeout = 30,
				func = "akill.predator_god_spawn()"
			},
			[7]	= {
				timeout = 5,
				func = "akill.predator_god_delete()"
			},
			[8]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_puzir_30_8_0"),
				tip_snd = [[sms\strelok\battle_puzir_30_8]],
			},
			[9]	= {
				timeout = 7,
				func = "akill.predator_vizor()"
			},
			[10]	= {
				timeout = 2,
				func = "akill.predator_target()"
			},
			[11]	= {
				timeout = 5,
				func = "akill.predator_hit()"
			},
			[12]	= {
				timeout = 30,
				func = "akill.predator_god_spawn()"
			},
			[13]	= {
				timeout = 6,
				func = "akill.predator_god_delete()"
			},
			[14]	= {
				timeout = 11,
				func = "akill.predator_zvuk()"
			},
			[15]	= {
				timeout = 3,
				func = "akill.predator_npc_spawn()"
			},
			[16]	= {
				timeout = 7,
				func = "akill.predator_vizor()"
			},
			[17]	= {
				timeout = 2,
				func = "akill.predator_target()"
			},
			[18]	= {
				func = "akill.predator_gauss()"
			}
		},
		[31] = {
			[1]	= {
				timeout = 18
			},
			[2]	= {
				timeout = 3,
				func = "akill.predator_bum()"
			},
			[3]	= {
				func = "akill.predator_npc_delete()"
			}
		},
-- Засада военных в ЗЛ
		[32] = {
			[1]	= {
				timeout = 15
			},
			[2]	= {
				timeout = 8,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_puzir_32_2_0"),
				tip_snd = [[sms\strelok\battle_puzir_32_2]],
			},
			[3]	= {
				timeout = 23,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_puzir_32_3_0"),
				tip_snd = [[sms\net\battle_puzir_32_3]],
			},
			[4]	= {
				timeout = 13,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_puzir_32_4_0"),
				tip_snd = [[sms\net\battle_puzir_32_4]],
			},
			[5]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_puzir_32_5_0"),
				tip_snd = [[sms\net\battle_puzir_32_5]],
			},
			[6]	= {
				timeout = 2,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_puzir_32_6_0"),
				tip_snd = [[sms\strelok\battle_puzir_32_6]],
			},
			[7]	= {
				func = "akill.zasada_puzir_spawn()"
			}
		}
	},
-- Ответный удар
	l12_stancia = {
		[30] = {
			[1]	= {
				timeout = 4
			},
			[2]	= {
				timeout = 4,
				func = "akill.strike_back_bum1()",
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_stancia_30_2_0"),
				tip_snd = [[sms\strelok\battle_stancia_30_2]],
			},
			[3]	= {
				timeout = 4,
				func = "akill.strike_back_bum2()"
			},
			[4]	= {
				timeout = 4,
				func = "akill.strike_back_bum3()"
			},
			[5]	= {
				timeout = 4,
				func = "akill.strike_back_bum4()"
			},
			[6]	= {
				timeout = 4,
				func = "akill.strike_back_bum5()"
			},
			[7]	= {
				timeout = 4,
				func = "akill.strike_back_bum6()"
			},
			[8]	= {
				timeout = 15,
				func = "akill.strike_back_bum7()"
			},
			[9]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_stancia_30_9_0"),
				tip_snd = [[sms\strelok\battle_stancia_30_9]],
				func = "akill.strike_back_zasada()"
			},
			[10]	= {
				timeout = 16,
				tip = "%c[sender]"..translate("name_korsar")..":\\n%c[sms_red]"..translate("battle_stancia_30_10_0"),
				tip_snd = [[sms\korsar\battle_stancia_30_10]],
				func = "akill.strike_back_end()"
			},
			[11]	= {
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_stancia_30_11_0"),
				tip_snd = [[sms\strelok\battle_stancia_30_11]],
			}
		}
	},
-- Остаться в живых
	l08_yantar = {
		[30] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 13,
				func = "akill.survival_quest_sms()"
			},
			[3]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_yantar_30_3_0"),
				tip_snd = [[sms\strelok\battle_yantar_30_3]],
			},
			[4]	= {
				timeout = 25,
				info = "survival_quest_start",
				func = "akill.survival_quest_start()"
			},
			[5]	= {
				timeout = 40,
				func = "akill.survival_quest_start()"
			},
			[6]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied"] = 1
		 		}
			},
			[7]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied1"] = 1
		 		}
			},
			[8]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied2"] = 1
		 		}
			},
			[9]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied3"] = 1
		 		}
			},
			[10]	= {
				timeout = 100,
				func = "akill.zombie_module_spawn()",
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["zombie_plague_komar"] = 1,
					["psyonik"] = 1,
					["girl_zombied3"] = 1
		 		}
			},
			[11]	= {
				timeout = 15,
				func = "akill.survival_quest_sms2()"
			},
			[12]	= {
				timeout = 15,
				info = "survival_quest_done",
				func = "akill.survival_quest_present()"
			},
			[13]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_yantar_30_13_0"),
				tip_snd = [[sms\strelok\battle_yantar_30_13]],
			},
			[14]	= {
				tip = "%c[sender]"..translate("name_operator_svyazi")..":\\n%c[sms_red]"..translate("battle_yantar_30_14_0"),
				tip_snd = [[sms\net\battle_yantar_30_14]],
			}
		}
	},
-- Akill end
    jupiter = {
        [1] = {
            [1]    = {
                dist = 60,
                timeout = 75,
                enemy = {
                    ["flesh_swamp"] = 4
				}
			},
			[2]	= {
				dist = 60,
				timeout = 120,
				enemy = {
					["zombie_babka_weak"] = 2,
					["zombie_babka_normal"] = 2,
 					["zombie_babka_strong"] = 2,
 					["m_gigant_jumper_e"] = 2, 
 					["zombie_hell15"] = 1,
 					["zombie_hell3"] = 1,
 					["zombie_hell4"] = 1,
 					["zombie_hell5"] = 1,
 					["zombie_hell"] = 1,
 					["zombie_hell6"] = 1,
 					["zombie_hell2"] = 2
				}
			},
			[3]	= {
				dist = 80,
				timeout = 90,
				enemy = {
					["snork_stronger"] = 1,
					["snork_strong"] = 2,
					["snork_jumper"] = 1,
					["snork_nosach"] = 2,
					["vypolzen"] = 2,
 					["vypolzen_red"] = 2,
 					["gigant_virus_strong"] = 1,
 					["gigant_super_jumper"] = 2
				}
			},
			[4]	= {
				dist = 90,
				enemy = {
					["electro_chimera"] = 1,
					["chimera_x_ray"] = 2,
 					["chimera_wolf"] = 2,
					["chimera_weak"] = 2,
					["new_electro_chimera"] = 1,
 					["fire_chimera"] = 1,
 					["bear"] = 1,
 					["lican"] = 1,
 					["bloodsucker_hell"] = 2,
 					["gigant_super_jumper"] = 2                                                   
				}
			}
		},
-- Akill begin
-- Охота на оборотней
		[30] = {
			[1]	= {
				timeout = 100
			},
			[2]	= {
				timeout = 140,
				dist = 70,
				enemy = {
					["chimera_wolf"] = 10
		 		}
			},
			[3]	= {
				dist = 70,
				enemy = {
					["ohota_wolf1"] = 1,
					["ohota_wolf2"] = 1
				}
			}
		},
-- Сделка с наёмниками
		[31] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_31_2_0"),
				tip_snd = [[sms\strelok\battle_jupiter_31_2]],
			},
			[3]	= {
				timeout = 30,
				tip = "%c[sender]"..translate("name_akill")..":\\n%c[sms_red]"..translate("battle_jupiter_31_3_0"),
				tip_snd = [[sms\akill\battle_jupiter_31_3]],
			},
			[4]	= {
				info = "mercenary_dogovor_have",
				func = "akill.mercenary_dogovor_spawn()",
				tip = "%c[sender]"..translate("name_akill")..":\\n%c[sms_red]"..translate("sms_battle_6_0")
			}
		},
-- Живые мертвецы
		[33] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["zombie_immortal"] = 2,
					["zombie_hell10"] = 2,
					["zombie_hell11"] = 2,
					["zombie_hell12"] = 2,
					["zombie_hell13"] = 1,
					["zombie_hell15"] = 1,
					["zombie_hell"] = 1,
					["zombie_plague_komar"] = 1,
					["zombie_plague"] = 1,
					["zombie_ghost"] = 2
		 		}
			},
			[3]	= {
				dist = 60,
				timeout = 15,
				enemy = {
					["vodjanoj"] = 1,
					["ghoul_strong"] = 2,
					["zombie_trup2"] = 2,
					["zombie_strong"] = 2,
					["zombie_weak"] = 2,
					["girl_zombied1"] = 1,
					["girl_zombied2"] = 1,
					["pri_under_zombied1"] = 1,
					["zombie_blow"] = 1,
					["zombie_hell1"] = 1,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_2"] = 1
				}
			},
			[4]	= {
				tip = "%c[sender]"..translate("name_vanka_rizhii")..":\\n%c[sms_red]"..translate("battle_jupiter_33_4_0"),
				tip_snd = [[sms\battle\battle_jupiter_33_4]],
				dist = 41,
				timeout = 60,
				enemy = {
					["bar_stalker_respawn_2"] = 1,
					["gar_stalker_respawn_2"] = 1,
					["agr_stalker_regular"] = 1,
					["agr_stalker_veteran"] = 1,
					["gar_stalker_respawn_1"] =1,
					["gar_dolg_respawn_1"] = 1,
					["gar_dolg_respawn_2"] = 1,
					["bar_stalker_respawn_1"] = 1
				}
			},
			[5]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["vodjanoj"] = 1,
					["zombie_hell1"] = 2,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["zombie_hell6"] = 2,
					["zombie_hell7"] = 2,
					["zombie_hell8"] = 2,
					["zombie_hell9"] = 1,
					["zombie_beee"] = 1,
					["zombie_hell15"] = 1,
					["zombie_plague_komar"] = 1,
					["upi_eco_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_3"] = 1
				}
			},
			[6]	= {
				dist = 60,
				timeout = 20,
				enemy = {
					["zombie_hell5"] = 2,
					["zombie_hell6"] = 2,
					["zombie_hell7"] = 2,
					["zombie_hell8"] = 2,
					["zombie_hell9"] = 2,
					["zombie_weak"] = 2,
					["zombie_plague"] = 1,
					["zombie_hell13"] = 2,
					["zombie_hell12"] = 2,
					["zombie_strong"] = 2,
					["zombie_ghost"] = 2,
					["zombie_immortal"] = 1,
					["girl_zombied2"] = 1,
					["zombie_hell"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 2,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["upi_eco_zombied2"] = 1,
					["pri_under_zombied2"] = 1
				}
			},
			[7]	= {
				tip = "%c[sender]"..translate("name_senya_hitrii")..":\\n%c[sms_red]"..translate("battle_jupiter_33_7_0"),
				tip_snd = [[sms\battle\battle_jupiter_33_7]],
				dist = 41,
				timeout = 100,
				enemy = {
					["mil_freedom_respawn_sniper"] = 1,
					["gar_stalker_respawn_2"] = 1,
					["agr_stalker_regular"] = 1,
					["agr_stalker_veteran"] = 1,
					["gar_stalker_respawn_1"] = 1,
					["mil_freedom_respawn_1"] = 1,
					["mil_freedom_respawn_2"] = 1,
					["mil_freedom_respawn_3"] = 1
				}
			},
			[8]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["vodjanoj"] = 2,
					["zombie_hell13"] = 2,
					["zombie_hell12"] = 2,
					["zombie_strong"] = 2,
					["rad_zombied_respawn_2"] = 1,
					["zombie_ghost"] = 2,
					["zombie_immortal"] = 2,
					["zombie_hell1"] = 1,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["girl_zombied3"] = 1,
					["girl_zombied"] = 1,
					["zombie_hell15"] = 1,
					["zombie_blow"] = 1,
					["zombie_plague_komar"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["upi_eco_zombied3"] = 1,
					["pri_under_zombied3"] = 1
				}
			},
			[9]	= {
				dist = 60,
				timeout = 20,
				enemy = {
					["zombie_hell1"] = 2,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["zombie_hell6"] = 2,
					["zombie_hell7"] = 2,
					["zombie_hell8"] = 2,
					["zombie_hell9"] = 2,
					["zombie_hell10"] = 2,
					["zombie_hell11"] = 2,
					["zombie_hell12"] = 2,
					["zombie_hell13"] = 1,
					["zombie_plague"] = 1,
					["zombie_beee"] = 1,
					["zombie_ghost"] = 2,
					["girl_zombied"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_1"] = 1,
					["pri_under_zombied3"] = 1
				}
			},
			[10]	= {
				tip = "%c[sender]"..translate("name_roma_buldog")..":\\n%c[sms_red]"..translate("battle_jupiter_33_10_0"),
				tip_snd = [[sms\battle\battle_jupiter_33_10]],
				dist = 41,
				timeout = 100,
				enemy = {
					["bar_ohotnik_respawn_1"] = 1,
					["gar_stalker_respawn_2"] = 1,
					["agr_stalker_regular"] = 1,
					["agr_stalker_veteran"] = 1,
					["gar_stalker_respawn_1"] = 1,
					["forest_nebo_regular"] = 1,
					["forest_nebo_veteran"] = 1,
					["forest_nebo_master"] = 1
				}
			},
			[11]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["zombie_hell10"] = 2,
					["zombie_hell11"] = 2,
					["zombie_hell12"] = 2,
					["zombie_hell13"] = 2,
					["zombie_ghost"] = 2,
					["zombie_immortal"] = 2,
					["zombie_strong"] = 2,
					["ghoul_strong"] = 2,
					["zombie_trup2"] = 1,
					["zombie_hell1"] = 2,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["zombie_hell15"] = 1,
					["zombie_hell"] = 1,
					["zombie_plague_komar"] = 1,
					["upi_eco_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_2"] = 2,
					["pri_under_zombied1"] = 1
				}
			},
			[12]	= {
				dist = 60,
				enemy = {
					["zombie_hell1"] = 1,
					["zombie_hell2"] = 1,
					["zombie_hell3"] = 1,
					["zombie_hell4"] = 1,
					["zombie_hell5"] = 1,
					["zombie_hell6"] = 1,
					["zombie_hell7"] = 1,
					["zombie_hell8"] = 1,
					["zombie_plague"] = 1,
					["zombie_blow"] = 1,
					["controller_senator"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["ohota_zombi1"] = 1,
					["ohota_zombi2"] = 1
				}
			}
		},
-- С небес на землю
		[35] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				timeout = 30,
				func = "akill.volna_bpla_help()"
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_35_3_0"),
				tip_snd = [[sms\strelok\battle_jupiter_35_3]],
			},
			[4]	= {
				tip = "%c[sender]"..translate("name_sidorovich")..":\\n%c[sms_red]"..translate("battle_jupiter_35_4_0"),
				tip_snd = [[sms\sidor\battle_jupiter_35_4]],
			}
		},
-- Кротовая нора
		[36] = {
			[1]	= {
				timeout = 90
			},
			[2]	= {
				timeout = 70,
				func = "akill.sak_tunnels_tp()"
			},
			[3]	= {
				timeout = 60,
				func = "akill.sak_monolit_tp()"
			},
			[4]	= {
				timeout = 80,
				func = "akill.sak_zvuk()",
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_36_4_0"),
				tip_snd = [[sms\strelok\battle_jupiter_36_4]],
			},
			[5]	= {
				timeout = 60,
				func = "akill.sak_gigant_tp()"
			},
			[6]	= {
				timeout = 60,
				func = "akill.sak_zvuk()"
			},
			[7]	= {
				timeout = 40,
				func = "akill.sak_bolota_tp()"
			},
			[8]	= {
				timeout = 50,
				func = "akill.sak_zvuk()"
			},
			[9]	= {
				timeout = 40,
				func = "akill.sak_new_hell_tp()",
				info = "volna_sak_test"
			},
			[10]	= {
				timeout = 40,
				func = "akill.sak_zvuk()"
			},
			[11]	= {
				timeout = 100,
				func = "akill.sak_zombie_tp()"
			},
			[12]	= {
				timeout = 70,
				func = "akill.sak_biblik_tp()"
			},
			[13]	= {
				timeout = 70,
				func = "akill.sak_zvuk()"
			},
			[14]	= {
				timeout = 4,
				func = "akill.sak_polet_tp()",
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_36_14_0"),
				tip_snd = [[sms\strelok\battle_jupiter_36_14]],
			},
			[15]	= {
				timeout = 2,
				func = "akill.sak_kopachi_tp()"
			},
			[16]	= {
				timeout = 10,
				func = "akill.sak_effect()"
			},
			[17]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_36_17_0"),
				tip_snd = [[sms\strelok\battle_jupiter_36_17]],
			},
			[18]	= {
				func = "akill.volna_sak_have()"
			}
		},
-- Перевёртыши, битва с ротанами на болоте
		[37] = {
			[1]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_37_1_0"),
				tip_snd = [[sms\strelok\battle_jupiter_37_1]],
			},
			[2]	= {
				timeout = 7,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_37_2_0"),
				tip_snd = [[sms\strelok\battle_jupiter_37_2]],
			},
			[3]	= {
				timeout = 7,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_37_3_0"),
				tip_snd = [[sms\strelok\battle_jupiter_37_3]],
				func = "akill.rotan_spawn()"
			},
			[4]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_37_4_0"),
				tip_snd = [[sms\strelok\battle_jupiter_37_4]],
			},
			[5]	= {
				timeout = 40,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_jupiter_37_5_0"),
				tip_snd = [[sms\net\battle_jupiter_37_5]],
			},
			[6]	= {
				timeout = 10,
				func = "akill.rotan_spawn()"
			},
			[7]	= {
				timeout = 7,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_jupiter_37_7_0"),
				tip_snd = [[sms\net\battle_jupiter_37_7]],
				func = "akill.rotan_help_spawn()"
			},
			[8]	= {
				timeout = 30,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_37_8_0"),
				tip_snd = [[sms\strelok\battle_jupiter_37_8]],
			},
			[9]	= {
				timeout = 60,
				func = "akill.rotan_spawn()"
			},
			[10]	= {
				timeout = 60,
				func = "akill.rotan_spawn()"
			},
			[11]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_37_11_0"),
				tip_snd = [[sms\strelok\battle_jupiter_37_11]],
			},
			[12]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_jupiter_37_12_0"),
				tip_snd = [[sms\net\battle_jupiter_37_12]],
			},
			[13]	= {
				timeout = 10,
				func = "akill.ballast_delete()",
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_jupiter_37_13_0"),
				tip_snd = [[sms\strelok\battle_jupiter_37_13]],
			},
			[14]	= {
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_jupiter_37_14_0"),
				tip_snd = [[sms\net\battle_jupiter_37_14]],			
			}
		}
	},
-- Трудная мишень
	red_forest = {
		[30] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				dist = 41,
				timeout = 50,
				func = "akill.volna_zahar_start()",
				enemy = {
					["ohota_snork1"] = 1
		 		}
			},
			[3]	= {
				dist = 41,
				timeout = 60,
				func = "akill.volna_zahar_start()",
				enemy = {
					["snork_weak"] = 1,
					["ohota_snork2"] = 1
		 		}
			},
			[4]	= {
				dist = 41,
				timeout = 40,
				func = "akill.volna_zahar_start()",
				info = "no_pnv",
				enemy = {
					["snork_weak"] = 1
				}
			},
			[5]	= {
				dist = 41,
				enemy = {
					["ohota_snork3"] = 1
				}
			}
		},
-- Охота на выползней
		[31] = {
			[1]	= {
				timeout = 2
			},
			[2]	= {
				timeout = 2,
				func = "akill.ohota_vypolzen_bum1()"
			},
			[3]	= {
				timeout = 6,
				func = "akill.ohota_vypolzen_bum2()"
			},
			[4]	= {
				timeout = 11,
				tip = "%c[sender]"..translate("name_strelok")..":\\n%c[sms_red]"..translate("battle_red_forest_31_4_0"),
				tip_snd = [[sms\strelok\battle_red_forest_31_4]],
			},
			[5]	= {
				tip = "%c[sender]"..translate("name_lesnik")..":\\n%c[sms_red]"..translate("battle_red_forest_31_5_0"),
				tip_snd = [[sms\lesnik\battle_red_forest_31_5]],
				info = "ohota_vypolzen_spawn"
			}
		}
	},
-- Оборона комплекса
	l03_agroprom = {
		[30] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				timeout = 80,
				func = "akill.btr_elite_spawn()"
			},
			[3]	= {
				dist = 50,
				timeout = 30,
				enemy = {
					["zasada_tonnel_agro_1"] = 1,
					["zasada_tonnel_agro_2"] = 1,
					["zasada_tonnel_agro_3"] = 1,
					["zasada_blockpost_1"] = 1,
					["zasada_blockpost_2"] = 1,
					["zasada_blockpost_3"] = 1,
					["agro_elite_soldier"] = 1
		 		}
			},
			[4]	= {
				dist = 41,
				enemy = {
					["major_lisicyn"] = 1,
					["agro_elite_sniper1"] = 1
				}
			}
		},
-- Охота на грызунов
		[31] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				dist = 60,
				timeout = 55,
				enemy = {
					["winger"] = 5,
					["tushkano_normal"] = 8,
					["tushkano_strong"] = 7
		 		}
			},
			[3]	= {
				dist = 60,
				timeout = 55,
				enemy = {
					["ohota_tushkan2"] = 1,
					["winger"] = 5,
					["tushkano_normal"] = 8,
					["tushkano_strong"] = 7
		 		}
			},
			[4]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["winger"] = 5,
					["tushkano_normal"] = 8,
					["tushkano_strong"] = 7
		 		}
			},
			[5]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["winger"] = 5,
					["tushkano_normal"] = 8,
					["tushkano_strong"] = 7
		 		}
			},
			[6]	= {
				dist = 60,
				enemy = {
					["ohota_tushkan3"] = 1,
					["tushkano_normal"] = 1
		 		}
			}
		},
-- Огневая поддержка, ликвидация цели
		[32] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 9,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_32_2_0"),
				tip_snd = [[sms\strelok\battle_agroprom_32_2]],
			},
			[3]	= {
				timeout = 9,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_32_3_0"),
				tip_snd = [[sms\varg\battle_agroprom_32_3]],
			},
			[4]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_32_4_0"),
				tip_snd = [[sms\strelok\battle_agroprom_32_4]],
			},
			[5]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_32_5_0"),
				tip_snd = [[sms\varg\battle_agroprom_32_5]],
			},
			[6]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_32_6_0"),
				tip_snd = [[sms\strelok\battle_agroprom_32_6]],
			},
			[7]	= {
				timeout = 11,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_32_7_0"),
				tip_snd = [[sms\varg\battle_agroprom_32_7]],
			},
			[8]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_32_8_0"),
				tip_snd = [[sms\varg\battle_agroprom_32_8]],
			},
			[9]	= {
				timeout = 8,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_32_9_0"),
				tip_snd = [[sms\strelok\battle_agroprom_32_9]],
			},
			[10]	= {
				timeout = 4,
				func = "akill.varg_target_hit()"
			},
			[11]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_32_11_0"),
				tip_snd = [[sms\varg\battle_agroprom_32_11]],
			},
			[12]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_32_12_0"),
				tip_snd = [[sms\strelok\battle_agroprom_32_12]],
			},
			[13]	= {
				timeout = 15,
				func = "akill.varg_patrol1()",
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_32_13_0"),
				tip_snd = [[sms\varg\battle_agroprom_32_13]],
			},
			[14]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_32_14_0"),
				tip_snd = [[sms\varg\battle_agroprom_32_14]],
			},
			[15]	= {
				func = "akill.varg_patrol2()"
			}
		},
-- Не находим журнал полётов
		[33] = {
			[1]	= {
				timeout = 3
			},
			[2]	= {
				timeout = 11,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_33_2_0"),
				tip_snd = [[sms\strelok\battle_agroprom_33_2]],
			},
			[3]	= {
				timeout = 11,
				tip = "%c[sender]"..translate("name_akim")..":\\n%c[sms_red]"..translate("battle_agroprom_33_3_0"),
				tip_snd = [[sms\akim\battle_agroprom_33_3]],
			},
			[4]	= {
				timeout = 11,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_33_4_0"),
				tip_snd = [[sms\strelok\battle_agroprom_33_4]],
			},
			[5]	= {
				tip = "%c[sender]"..translate("name_akim")..":\\n%c[sms_red]"..translate("battle_agroprom_33_5_0"),
				tip_snd = [[sms\akim\battle_agroprom_33_5]],
			}
		},
-- Огневая поддержка, прикрываем Варга
		[34] = {
			[1]	= {
				timeout = 9
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_34_2_0"),
				tip_snd = [[sms\strelok\battle_agroprom_34_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_34_3_0"),
				tip_snd = [[sms\varg\battle_agroprom_34_3]],
			},
			[4]	= {
				timeout = 80,
				func = "akill.varg_soldier1()"
			},
			[5]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_agroprom_34_5_0"),
				tip_snd = [[sms\strelok\battle_agroprom_34_5]],
			},
			[6]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_varg")..":\\n%c[sms_red]"..translate("battle_agroprom_34_6_0"),
				tip_snd = [[sms\varg\battle_agroprom_34_6]],
			},
			[7]	= {
				func = "akill.varg_soldier2()"
			}
		}
	},
-- Находим Крюка
	pripyat = {
		[31] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 1,
				func = "akill.kruk_vystrel()"
			},
			[3]	= {
				timeout = 3,
				func = "akill.kruk_ranen()"
			},
			[4]	= {
				timeout = 3,
				func = "akill.kruk_vystrel()"
			},
			[5]	= {
				timeout = 15,
				func = "akill.kruk_vystrel()"
			},
			[6]	= {
				timeout = 12,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_pripyat_31_6_0"),
				tip_snd = [[sms\strelok\battle_pripyat_31_6]],
			},
			[7]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_barmen")..":\\n%c[sms_red]"..translate("battle_pripyat_31_7_0"),
				tip_snd = [[sms\barman\battle_pripyat_31_7]],
			},
			[8]	= {
				func = "akill.kruk_merki()",
				info = "volna_barmen_have"
			}
		},
-- Старая икона
		[32] = {
			[1]	= {
				timeout = 10
			},
			[2]	= {
				timeout = 70,
				func = "akill.volna_petrenko_spawn()"
			},
			[3]	= {
				dist = 65,
				enemy = {
					["zombie_hell3"] = 1,
					["zombie_hell4"] = 1,
					["zombie_hell5"] = 1,
					["zombie_hell6"] = 1,
					["zombie_hell15"] = 1,
					["girl_zombied1"] = 1,
					["girl_zombied2"] = 1,
					["zombie_babka_strong"] = 1,
					["zombie_hell"] = 1,
					["zombie_beee"] = 1,
					["zombie_hell12"] = 1
		 		}
			}
		},
	},
-- Тайна Скряги
	l07_military = {
		[30] = {
			[1]	= {
				timeout = 40
			},
			[2]	= {
				func = "arhara_dialog.vrag_zombie(actor, npc)"
			}
		},
-- Подготовка на Затоне завершена
		[31] = {
			[1]	= {
				timeout = 13
			},
			[2]	= {
				timeout = 19,
				tip = "%c[sender]"..translate("name_vasilii")..":\\n%c[sms_red]"..translate("battle_military_31_2_0"),
				tip_snd = [[sms\vasiliy\battle_military_31_2]],
			},
			[3]	= {
				timeout = 20,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_31_3_0"),
				tip_snd = [[sms\strelok\battle_military_31_3]],
			},
			[4]	= {
				timeout = 16,
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("battle_military_31_4_0"),
				tip_snd = [[sms\noy\battle_military_31_4]],
			},
			[5]	= {
				timeout = 16,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_31_5_0"),
				tip_snd = [[sms\strelok\battle_military_31_5]],
			},
			[6]	= {
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("battle_military_31_6_0"),
				tip_snd = [[sms\noy\battle_military_31_6]],
			}
		},
-- Дом духов
		[32] = {
			[1]	= {
				timeout = 85
			},
			[2]	= {
				timeout = 90,
				func = "akill.ohota_polter_battle1()"
			},
			[3]	= {
				timeout = 90,
				func = "akill.ohota_polter_battle2()"
			},
			[4]	= {
				timeout = 90,
				func = "akill.ohota_polter_battle3()"
			},
			[5]	= {
				func = "akill.ohota_polter_battle4()"
			}
		},
-- Из огня да в полымя
		[33] = {
			[1]	= {
				timeout = 40
			},
			[2]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_2_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_2]],
			},
			[3]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_3_0"),
				tip_snd = [[sms\strelok\battle_military_33_3]],
			},
			[4]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_4_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_4]],
			},
			[5]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_5_0"),
				tip_snd = [[sms\strelok\battle_military_33_5]],
			},
			[6]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_6_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_6]],
			},
			[7]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_7_0"),
				tip_snd = [[sms\strelok\battle_military_33_7]],
			},
			[8]	= {
				timeout = 50,
				func = "akill.sledopyt_bomba_bw1()"
			},
			[9]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_9_0"),
				tip_snd = [[sms\strelok\battle_military_33_9]],
			},
			[10]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_10_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_10]],
			},
			[11]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_11_0"),
				tip_snd = [[sms\strelok\battle_military_33_11]],
			},
			[12]	= {
				timeout = 7,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_12_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_12]],
			},
			[13]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_13_0"),
				tip_snd = [[sms\strelok\battle_military_33_13]],
			},
			[14]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_14_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_14]],
			},
			[15]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_15_0"),
				tip_snd = [[sms\strelok\battle_military_33_15]],
			},
			[16]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_16_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_16]],
			},
			[17]	= {
				timeout = 4,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_17_0"),
				tip_snd = [[sms\strelok\battle_military_33_17]],
			},
			[18]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_18_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_18]],
			},
			[19]	= {
				timeout = 7,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_19_0"),
				tip_snd = [[sms\strelok\battle_military_33_19]],
			},
			[20]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_20_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_20]],
			},
			[21]	= {
				timeout = 6,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_21_0"),
				tip_snd = [[sms\strelok\battle_military_33_21]],
			},
			[22]	= {
				timeout = 7,
				func = "akill.sledopyt_bomba_bw2()",
				tip = "%c[sender]"..translate("name_sledopit")..":\\n%c[sms_red]"..translate("battle_military_33_22_0"),
				tip_snd = [[sms\sledopyt\battle_military_33_22]],
			},
			[23]	= {
				timeout = 7,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_military_33_23_0"),
				tip_snd = [[sms\strelok\battle_military_33_23]],
			},
			[24]	= {
				info = "sledopyt_bomba_have"
			}
		}
	},
	zaton = {
-- Доводы Ноя
		[32] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["boar_strong"] = 2,
					["boar_kachok"] = 2,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 2,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 1,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[3]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["dog_habaruch"] = 3,
					["dog_sil_hill"] = 3,
					["dog_skeleton"] = 4,
					["dog_green"] = 3,
					["dog_strong"] = 3,
					["dog_zombie"] = 3,
					["volkodav"] = 2,
					["pseudodog_big"] = 2,
					["pseudodog_strong"] = 3
				}
			},
			[4]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["cat_strong"] = 2,
					["cat_normal"] = 2,
					["cat_weak"] = 2,
					["psy_dog"] = 1,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["vypolzen_red"] = 2,
					["vypolzen"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["volkodav"] = 1,
					["pseudodog_big"] = 1,
					["pseudodog_strong"] = 2
				}
			},
			[5]	= {
				dist = 70,
				timeout = 80,
				enemy = {
					["bloodsucker_effector"] = 1,
					["oboroten"] = 2,
					["stinger"] = 5,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 2
				}
			},
			[6]	= {
				dist = 70,
				timeout = 80,
				enemy = {
					["deathclaw_normal"] = 1,
					["deathclaw_weak"] = 1,
					["deathclaw_strong"] = 1,
					["new_hell"] = 1,
 					["bear"] = 1,
 					["lican"] = 2,
					["chimera_normal"] = 2
				}
			},
			[7]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["electro_chimera"] = 1,
					["chimera_x_ray"] = 1,
					["chimera_wolf"] = 1,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_black"] = 1,
					["chimera_strong"] = 1
				}
			},
			[8]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["fracture_normal"] = 3,
					["karlito"] = 2,
					["psyonik"] = 1,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 2,
					["snork_stronger"] = 2
				}
			},
			[9]	= {
				dist = 70,
				enemy = {
					["kontrik_yantar1"] = 1,
					["kontrik_yantar2"] = 1,
					["poltergeist_build"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["kontrik_labx16"] = 1
				}
			}
		},
-- Подготовка к волне
		[33] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 17,
				tip = "%c[sender]"..translate("name_obschaya_set")..":\\n%c[sms_red]"..translate("battle_zaton_33_2_0"),
				tip_snd = [[sms\noy\battle_zaton_33_2]],
			},
			[3]	= {
				timeout = 12,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_33_3_0"),
				tip_snd = [[sms\strelok\battle_zaton_33_3]],
			},
			[4]	= {
				timeout = 17,
				tip = "%c[sender]"..translate("name_arni")..":\\n%c[sms_red]"..translate("battle_zaton_33_4_0"),
				tip_snd = [[sms\arni\battle_zaton_33_4]], 			
			},
			[5]	= {
				timeout = 12,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_33_5_0"),
				tip_snd = [[sms\strelok\battle_zaton_33_5]],
			},
			[6]	= {
				timeout = 12,
				tip = "%c[sender]"..translate("name_adrenalin")..":\\n%c[sms_red]"..translate("battle_zaton_33_6_0"),
				tip_snd = [[sms\adrenalin\battle_zaton_33_6]],
			},
			[7]	= {
				timeout = 30,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_33_7_0"),
				tip_snd = [[sms\strelok\battle_zaton_33_7]],
			},
			[8]	= {
				tip = "%c[sender]"..translate("name_basti")..":\\n%c[sms_red]"..translate("battle_zaton_33_8_0"),
				tip_snd = [[sms\buusty\battle_zaton_33_8]],
			}
		},
-- Секунды до смерти
		[34] = {
			[1]	= {
				timeout = 400
			},
			[2]	= {
				func = "akill.saper_code_fail()"
			}
		},
-- Встреча с Blackwater
		[35] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 11,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_35_2_0"),
				tip_snd = [[sms\strelok\battle_zaton_35_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_akill")..":\\n%c[sms_red]"..translate("battle_zaton_35_3_0"),
				tip_snd = [[sms\akill\battle_zaton_35_3]],
			},
			[4]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_35_4_0"),
				tip_snd = [[sms\strelok\battle_zaton_35_4]],
			},
			[5]	= {
				tip = "%c[sender]"..translate("name_akill")..":\\n%c[sms_red]"..translate("battle_zaton_35_5_0"),
				tip_snd = [[sms\akill\battle_zaton_35_5]],
			}
		},
-- Волна: день нулевой
		[36] = {
			[1]	= {
				timeout = 6
			},
			[2]	= {
				timeout = 45,
				func = "akill.volna_day0_spawn()",
				tip = "%c[sender]"..translate("name_kruglov")..":\\n%c[sms_red]"..translate("battle_zaton_36_2_0"),
				tip_snd = [[sms\kruglov\battle_zaton_36_2]],
			},
			[3]	= {
				func = "akill.volna_day0_spawn()"
			}
		},
-- Волна: день первый
		[37] = {
			[1]	= {
				info = "volna_goodwill",
				timeout = 9
			},
			[2]	= {
				timeout = 17,
				func = "akill.volna_day1_sound()",
				tip = "%c[sender]"..translate("name_kruglov")..":\\n%c[sms_red]"..translate("battle_zaton_37_2_0"),
				tip_snd = [[sms\kruglov\battle_zaton_37_2]],
			},
			[3]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("battle_zaton_37_3_0"),
				tip_snd = [[sms\noy\battle_zaton_37_3]],
			},
			[4]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("sms_battle_7_0")
			},
			[5]	= {
				timeout = 400,
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("sms_battle_8_0")
			},
			[6]	= {
				timeout = 15,
				func = "akill.volna_day1_dogs()"
			},
			[7]	= {
				timeout = 80,
				func = "akill.volna_day1_dogs()"
			},
			[8]	= {
				timeout = 80,
				info = "noi_defenders_otboi",
				func = "akill.volna_day1_boars()"
			},
			[9]	= {
				timeout = 80,
				func = "akill.volna_day1_boars()"
			},
			[10]	= {
				timeout = 80,
				func = "akill.volna_day1_dogs()"
			},
			[11]	= {
				timeout = 80,
				func = "akill.volna_day1_dogs()"
			},
			[12]	= {
				dist = 95,
				timeout = 140,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["rotan"] = 4,
					["kikimora"] = 3,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[13]	= {
				dist = 95,
				timeout = 140,
				enemy = {
					["boar_strong"] = 4,
					["boar_kachok"] = 4,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["rotan"] = 4,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[14]	= {
				dist = 95,
				timeout = 90,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["volkodav"] = 2,
					["psy_dog"] = 1,
					["pseudodog_strong"] = 5
				}
			},
			[15]	= {
				dist = 95,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 3,
					["stinger"] = 5,
					["volkodav"] = 2,
					["pseudodog_big"] = 3,
					["pseudodog_strong"] = 3
				}
			},
			[16]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_16_1_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_16_1]],
				rest = true,
				rukzak = true,
				timeout = 50,
				items = {
					["medkit"] = 4,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 3
				}
			},
			[17]	= {
				dist = 90,
				timeout = 30,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 3,
					["cat_weak"] = 4,
					["snork_strong"] = 4,
					["snork_stronger"] = 1,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["fracture_karlik"] = 5
				}
			},
			[18]	= {
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_zaton_37_18_0"),
				tip_snd = [[sms\net\battle_zaton_37_18]],
				dist = 60,
				timeout = 10,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[19]	= {
				dist = 60,
				timeout = 50,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[20]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 4,
					["cat_weak"] = 3,
					["snork_strong"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["gigant_strong"] = 2
				}
			},
			[21]	= {
				dist = 100,
				timeout = 120,
				enemy = {
					["cat_strong"] = 5,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["snork_strong"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["vypolzen"] = 4,
					["vypolzen_red"] = 4,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["fracture_karlik"] = 6
				}
			},
			[22]	= {
				dist = 95,
				timeout = 140,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 3,
					["chimera_wolf"] = 3,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["bloodsucker_effector"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1
				}
			},
			[23]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 3,
					["bloodsucker_mil"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_strong"] = 3,
					["bloodsucker_child"] = 2
				}
			},
			[24]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["electro_chimera"] = 6,
					["chimera_x_ray"] = 6,
					["chimera_wolf"] = 6,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 4,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 4
				}
			},
			[25]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 5,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_hell"] = 1
				}
			},
			[26]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_26_1_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_26_1]],
				rest = true,
				rukzak = true,
				timeout = 70,
				items = {
					["medkit_army"] = 4,
					["ammo_23x76_shrap"] = 2,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 4
				}
			},
			[27]	= {
				dist = 90,
				timeout = 30,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[28]	= {
				dist = 60,
				timeout = 15,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[29]	= {
				dist = 60,
				timeout = 80,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[30]	= {
				dist = 90,
				timeout = 150,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 2
				}
			},
			[31]	= {
				dist = 95,
				timeout = 150,
				enemy = {
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 4,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_hell"] = 2
				}
			},
			[32]	= {
				dist = 90,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["deathclaw_weak"] = 3,
					["deathclaw_normal"] = 3
				}
			},
			[33]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_strong"] = 3
				}
			},
			[34]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 1
				}
			},
			[35]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_35_1_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_35_1]],
				rest = true,
				rukzak = true,
				timeout = 70,
				items = {
					["medkit_scientic"] = 5,
					["ammo_balon"] = 4,
					["ammo_23x76_shrap"] = 3,
					["ammo_12.7x108r"] = 4,
					["ammo_minigun"] = 6
				}
			},
			[36]	= {
				dist = 100,
				timeout = 30,
				enemy = {
					["bloodsucker_hell"] = 3,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 3
				}
			},
			[37]	= {
				dist = 60,
				timeout = 200,
				enemy = {
					["freedom_volna"] = 5
				}
			},
			[38]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["bloodsucker_hell"] = 2,
					["oboroten"] = 2,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[39]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["kontrik_yantar1"] = 1,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 1,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[40]	= {
				dist = 90,
				timeout = 180,
				enemy = {
					["deathclaw_strong"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["new_hell"] = 2,
					["vypolzen"] = 8,
					["vypolzen_red"] = 8,
					["snork_stronger"] = 4,
					["snork_jumper"] = 5,
					["snork_nosach"] = 4,
					["snork_strong"] = 5
				}
			},
			[41]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["new_hell"] = 5,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_strong"] = 2,
					["bloodsucker_hell"] = 5,
					["oboroten"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 4,
					["bloodsucker_effector"] = 5,
					["bloodsucker_strong"] = 5
				}
			},
			[42]	= {
				dist = 90,
				timeout = 30,
				enemy = {
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 1,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_normal"] = 2,
					["chimera_strong"] = 1,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 1,
 					["lican"] = 1,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[43]	= {
				dist = 60,
				timeout = 200,
				enemy = {
					["freedom_volna"] = 5
				}
			},
			[44]	= {
				dist = 90,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2
				}
			},
			[45]	= {
				dist = 90,
				timeout = 220,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 2,
					["kontrik_yantar2"] = 1,
					["kontrik_labx16"] = 1,
					["controller_babka"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["deathclaw_strong"] = 1,
					["deathclaw_weak"] = 1,
					["deathclaw_normal"] = 1,
					["vypolzen"] = 5,
					["vypolzen_red"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[46]	= {
				dist = 70,
				enemy = {
					["kontrik_senator"] = 1
				}
	    	}
		},
-- Волна: день первый окончен
		[38] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 16,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_38_2_0"),
				tip_snd = [[sms\strelok\battle_zaton_38_2]],
			},
			[3]	= {
				timeout = 16,
				tip = "%c[sender]"..translate("name_sedoi")..":\\n%c[sms_red]"..translate("battle_zaton_38_3_0"),
				tip_snd = [[sms\sedoy\battle_zaton_38_3]],
			},
			[4]	= {
				timeout = 16,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_38_4_0"),
				tip_snd = [[sms\strelok\battle_zaton_38_4]],
			},
			[5]	= {
				tip = "%c[sender]"..translate("name_shura_ginekolog")..":\\n%c[sms_red]"..translate("battle_zaton_38_5_0"),
				tip_snd = [[sms\ginekolog\battle_zaton_38_5]],
			}
		},
-- Волна: день второй начался
		[39] = {
			[1]	= {
				timeout = 15
			},
			[2]	= {
				timeout = 20,
				tip = "%c[sender]"..translate("name_kruglov")..":\\n%c[sms_red]"..translate("battle_zaton_39_2_0"),
				tip_snd = [[sms\kruglov\battle_zaton_39_2]],
			},
			[3]	= {
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("battle_zaton_39_3_0"),
				tip_snd = [[sms\noy\battle_zaton_39_3]],
			}
		},
-- Волна: день второй
		[40] = {
			[1]	= {
				info = "volna_goodwill",
				timeout = 15
			},
			[2]	= {
				timeout = 400,
				tip = "%c[sender]"..translate("name_kruglov")..":\\n%c[sms_red]"..translate("battle_zaton_40_2_0"),
				tip_snd = [[sms\kruglov\battle_zaton_40_2]],
			},
			[3]	= {
				timeout = 20,
				func = "akill.volna_day2_dogs()"
			},
			[4]	= {
				timeout = 60,
				func = "akill.volna_day2_dogs()"
			},
			[5]	= {
				timeout = 60,
				func = "akill.volna_day2_boars()"
			},
			[6]	= {
				timeout = 70,
				func = "akill.volna_day2_boars()"
			},
			[7]	= {
				timeout = 70,
				func = "akill.volna_day2_dogs()"
			},
			[8]	= {
				timeout = 70,
				func = "akill.volna_day2_dogs()"
			},
			[9]	= {
				timeout = 70,
				func = "akill.volna_day2_boars()"
			},
			[10]	= {
				dist = 80,
				info = "kogot_defenders_otboi",
				timeout = 80,
				enemy = {
					["cat_strong"] = 4,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_strong"] = 3,
					["snork_jumper"] = 2,
					["snork_nosach"] = 3,
					["snork_stronger"] = 1,
					["fracture_strong"] = 6,
					["fracture_master"] = 6,
					["fracture_karlik"] = 6
				}
			},
			[11]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["bloodsucker_effector"] = 1,
					["oboroten"] = 2,
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 5,
					["chimera_wolf"] = 5,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_normal"] = 4,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 3
				}
			},
			[12]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["vypolzen"] = 8,
					["vypolzen_red"] = 8,
					["snork_stronger"] = 3,
					["snork_jumper"] = 5,
					["snork_nosach"] = 3,
					["snork_strong"] = 8
				}
			},
			[13]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 4,
					["fracture_master"] = 4,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 4,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_normal"] = 1
				}
			},
			[14]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_14_1_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_14_1]],
				rest = true,
				rukzak = true,
				timeout = 60,
				items = {
					["medkit"] = 4,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 3
				}
			},
			[15]	= {
				dist = 80,
				timeout = 30,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 3,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[16]	= {
				tip = "%c[sender]"..translate("name_lokalnaya_set")..":\\n%c[sms_red]"..translate("battle_zaton_40_16_0"),
				tip_snd = [[sms\net\battle_zaton_40_16]],
				dist = 60,
				timeout = 16,
				enemy = {
					["dolg_volna1"] = 1,
					["dolg_volna2"] = 1,
					["dolg_volna3"] = 1,
					["dolg_volna4"] = 1,
					["ohotnik_volna"] = 1
				}
			},
			[17]	= {
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_40_17_0"),
				tip_snd = [[sms\strelok\battle_zaton_40_17]],
				timeout = 12
			},
			[18]	= {
				dist = 80,
				timeout = 110,
				enemy = {
					["boar_strong"] = 4,
					["boar_kachok"] = 4,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[19]	= {
				dist = 80,
				timeout = 110,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[20]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 3,
					["cat_weak"] = 4,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_strong"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["gigant_strong"] = 2
				}
			},
			[21]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[22]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 2,
					["bloodsucker_strong"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_hell"] = 1
				}
			},
			[23]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 4,
					["fracture_master"] = 5,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 1
				}
			},
			[24]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_24_1_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_24_1]],
				rest = true,
				rukzak = true,
				timeout = 100,
				items = {
					["medkit_army"] = 4,
					["ammo_23x76_shrap"] = 2,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 4
				}
			},
			[25]	= {
				dist = 80,
				timeout = 40,
				enemy = {
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 3,
					["chimera_wolf"] = 3,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["bloodsucker_effector"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_strong"] = 4,
					["bloodsucker_child"] = 1
				}
			},
			[26]	= {
				dist = 60,
				timeout = 120,
				enemy = {
					["dolg_volna1"] = 1,
					["dolg_volna2"] = 1,
					["dolg_volna3"] = 1,
					["dolg_volna4"] = 1,
					["ohotnik_volna"] = 1
				}
			},
			[27]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[28]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
 					["bear"] = 3,
 					["lican"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 4,
					["chimera_strong"] = 4
				}
			},
			[29]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[30]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_hell"] = 1
				}
			},
			[31]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 3,
					["fracture_strong"] = 4,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_strong"] = 1,
					["deathclaw_weak"] = 1,
					["deathclaw_normal"] = 2
				}
			},
			[32]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_hell"] = 2
				}
			},
			[33]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 2
				}
			},
			[34]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("sms_battle_9_0"),
				rest = true,
				rukzak = true,
				timeout = 80,
				items = {
					["medkit_scientic"] = 5,
					["ammo_balon"] = 4,
					["ammo_23x76_shrap"] = 3,
					["ammo_12.7x108r"] = 4,
					["ammo_minigun"] = 6
				}
			},
			[35]	= {
				dist = 100,
				timeout = 40,
				enemy = {
					["bloodsucker_hell"] = 3,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 1,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 2,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 4
				}
			},
			[36]	= {
				dist = 60,
				timeout = 180,
				enemy = {
					["dolg_volna1"] = 1,
					["dolg_volna2"] = 1,
					["dolg_volna3"] = 1,
					["dolg_volna4"] = 1,
					["ohotnik_volna"] = 1
				}
			},
			[37]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bloodsucker_hell"] = 1,
					["oboroten"] = 1,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[38]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["kontrik_yantar1"] = 1,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[39]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["new_hell"] = 5,
					["deathclaw_strong"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["bloodsucker_hell"] = 5,
					["bloodsucker_child"] = 4,
					["oboroten"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_effector"] = 5,
					["bloodsucker_strong"] = 5
				}
			},
			[40]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_normal"] = 2,
					["chimera_strong"] = 1,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[41]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2
				}
			},
			[42]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 2,
					["kontrik_yantar2"] = 1,
					["kontrik_labx16"] = 1,
					["controller_babka"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["deathclaw_weak"] = 1,
					["deathclaw_normal"] = 1,
					["deathclaw_strong"] = 1,
					["vypolzen"] = 5,
					["vypolzen_red"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[43]	= {
				dist = 70,
				enemy = {
					["kontrik_senator"] = 1
				}
		    	}
		},
-- Штурм станции
		[41] = {
			[1]	= {
				timeout = 17,
				tip = "%c[sender]"..translate("name_feniks")..":\\n%c[sms_red]"..translate("battle_zaton_41_1_0"),
				tip_snd = [[sms\fenix\battle_zaton_41_1]],
			},
			[2]	= {
				timeout = 17,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_41_2_0"),
				tip_snd = [[sms\strelok\battle_zaton_41_2]],
			},
			[3]	= {
				tip = "%c[sender]"..translate("name_feniks")..":\\n%c[sms_red]"..translate("battle_zaton_41_3_0"),
				tip_snd = [[sms\fenix\battle_zaton_41_3]],
			}
		},
-- Волна: день третий
		[42] = {
			[1]	= {
				info = "volna_goodwill",
				timeout = 25
			},
			[2]	= {
				timeout = 400,
				tip = "%c[sender]"..translate("name_kruglov")..":\\n%c[sms_red]"..translate("battle_zaton_42_2_0"),
				tip_snd = [[sms\kruglov\battle_zaton_42_2]],
			},
			[3]	= {
				timeout = 40,
				func = "akill.volna_day3_boars()"
			},
			[4]	= {
				timeout = 120,
				func = "akill.volna_day3_chimera()"
			},
			[5]	= {
				timeout = 50,
				func = "akill.volna_day3_boars()"
			},
			[6]	= {
				timeout = 140,
				func = "akill.volna_day3_chimera()"
			},
			[7]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[8]	= {
				dist = 80,
				info = "fenix_defenders_otboi",
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[9]	= {
				dist = 80,
				timeout = 90,
				enemy = {
					["cat_strong"] = 4,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_strong"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["fracture_strong"] = 6,
					["fracture_master"] = 6,
					["fracture_karlik"] = 6
				}
			},
			[10]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["vypolzen"] = 9,
					["vypolzen_red"] = 9,
					["snork_stronger"] = 4,
					["snork_jumper"] = 5,
					["snork_nosach"] = 3,
					["snork_strong"] = 8
				}
			},
			[11]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bloodsucker_effector"] = 1,
					["oboroten"] = 1,
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 4,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 3
				}
			},
			[12]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[13]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 1,
					["fracture_strong"] = 4,
					["fracture_master"] = 4,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_weak"] = 1,
					["deathclaw_strong"] = 1,
					["deathclaw_normal"] = 1
				}
			},
			[14]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_14_2_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_14_2]],
				rest = true,
				rukzak = true,
				timeout = 60,
				items = {
					["medkit"] = 4,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 3
				}
			},
			[15]	= {
				dist = 80,
				timeout = 30,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[16]	= {
				dist = 60,
				timeout = 40,
				enemy = {
					["stalker_volna1"] = 1,
					["stalker_volna2"] = 1,
					["stalker_volna3"] = 1,
					["stalker_volna4"] = 1
				}
			},
			[17]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[18]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 4,
					["cat_weak"] = 3,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_strong"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["gigant_strong"] = 2
				}
			},
			[19]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 3,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 2,
					["gigant_jumper_strong"] = 4,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 2,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 2
				}
			},
			[20]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_mil"] = 1,
					["bloodsucker_hell"] = 2
				}
			},
			[21]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 3,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[22]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 1
				}
			},
			[23]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[24]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_24_2_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_24_2]],
				rest = true,
				rukzak = true,
				timeout = 100,
				items = {
					["medkit_army"] = 4,
					["ammo_23x76_shrap"] = 2,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 4
				}
			},
			[25]	= {
				dist = 80,
				timeout = 90,
				enemy = {
					["cat_strong"] = 4,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_strong"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 3,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["fracture_karlik"] = 6
				}
			},
			[26]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["stalker_volna1"] = 1,
					["stalker_volna2"] = 1,
					["stalker_volna3"] = 1,
					["stalker_volna4"] = 1
				}
			},
			[27]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[28]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 5,
					["chimera_x_ray"] = 5,
					["chimera_wolf"] = 5,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
 					["bear"] = 3,
 					["lican"] = 3,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 3
				}
			},
			[29]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[30]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 3,
					["chimera_wolf"] = 3,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_hell"] = 1
				}
			},
			[31]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 3,
					["fracture_strong"] = 4,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 3,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_weak"] = 1,
					["deathclaw_strong"] = 1,
					["deathclaw_normal"] = 1
				}
			},
			[32]	= {
				dist = 80,
				timeout = 190,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_effector"] = 1,
					["bloodsucker_strong"] = 4,
					["bloodsucker_child"] = 1
				}
			},
			[33]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 3,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 2
				}
			},
			[34]	= {
				ruk_sms = "%c[sender]"..translate("name_lovkach")..":\\n%c[sms_red]"..translate("battle_zaton_34_1_0"),
				ruk_snd = [[sms\lovkach\battle_zaton_34_1]],
				rest = true,
				rukzak = true,
				timeout = 80,
				items = {
					["medkit_scientic"] = 5,
					["ammo_balon"] = 4,
					["ammo_23x76_shrap"] = 3,
					["ammo_12.7x108r"] = 4,
					["ammo_minigun"] = 6
				}
			},
			[35]	= {
				dist = 100,
				timeout = 40,
				enemy = {
					["bloodsucker_hell"] = 3,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 1,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 2,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 4
				}
			},
			[36]	= {
				tip = "%c[sender]"..translate("name_slavka_antizombi")..":\\n%c[sms_red]"..translate("battle_zaton_42_36_0"),
				tip_snd = [[sms\antizombi\battle_zaton_42_36]],
				dist = 60,
				timeout = 180,
				enemy = {
					["slavka_volna"] = 1,
					["stalker_volna1"] = 1,
					["stalker_volna2"] = 1,
					["stalker_volna3"] = 1,
					["stalker_volna4"] = 1
				}
			},
			[37]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bloodsucker_hell"] = 1,
					["oboroten"] = 1,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 3,
					["deathclaw_weak"] = 3,
					["deathclaw_normal"] = 3,
					["deathclaw_strong"] = 3,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 4
				}
			},
			[38]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["kontrik_yantar1"] = 1,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 3,
					["deathclaw_weak"] = 3,
					["deathclaw_normal"] = 3,
					["deathclaw_strong"] = 3,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] =3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[39]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["new_hell"] = 5,
					["deathclaw_strong"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["bloodsucker_hell"] = 5,
					["bloodsucker_child"] = 4,
					["oboroten"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_effector"] = 5,
					["bloodsucker_strong"] = 4
				}
			},
			[40]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_normal"] = 2,
					["chimera_strong"] = 1,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[41]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 1,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2
				}
			},
			[42]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 2,
					["kontrik_yantar2"] = 1,
					["kontrik_labx16"] = 1,
					["controller_babka"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 3,
					["fracture_karlik"] = 3,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["vypolzen"] = 5,
					["vypolzen_red"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[43]	= {
				dist = 70,
				enemy = {
					["kontrik_senator"] = 1
				}
	    	}
		},
-- Волна: последняя битва началась
		[43] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_10_0")
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_43_3_0"),
				tip_snd = [[sms\strelok\battle_zaton_43_3]],
			},
			[4]	= {
				timeout = 16,
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_11_0")
			},
			[5]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_43_5_0"),
				tip_snd = [[sms\strelok\battle_zaton_43_5]],
			},
			[6]	= {
				timeout = 18,
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_12_0")
			},
			[7]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_43_7_0"),
				tip_snd = [[sms\strelok\battle_zaton_43_7]],
			},
			[8]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_43_8_0"),
				tip_snd = [[sms\strelok\battle_zaton_43_8]],
			},
			[9]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_noi")..":\\n%c[sms_red]"..translate("battle_zaton_43_9_0"),
				tip_snd = [[sms\noy\battle_zaton_43_9]],
			},
			[10]	= {
				info = "volna_goodwill",
				info = "volna_day4_start"
			}
		},
-- Волна: последняя битва, портовые краны
		[44] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 20,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_44_2_0"),
				tip_snd = [[sms\strelok\battle_zaton_44_2]],
			},
			[3]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["bloodsucker_volna"] = 2
		 		}
			},
			[4]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["deathclaw_volna"] = 2
				}
			},
			[5]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 3,
					["deathclaw_volna"] = 2
				}
			},
			[6]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 4,
					["chimera_wolf_volna"] = 3,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 1
				}
			},
			[7]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 3
				}
			},
			[8]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 2
				}
			},
			[9]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 4,
					["bloodsucker_volna"] = 5,
					["deathclaw_volna"] = 3
				}
			},
			[10]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 1
		 		}
			},
			[11]	= {
				dist = 50,
				timeout = 20,
				enemy = {
					["volna_biblik"] = 1
		 		}
			},
			[12]	= {
				timeout = 10,
				func = "akill.volna_day1_dogs()",
				tip = "%c[sender]"..translate("name_zhnets")..":\\n%c[sms_red]"..translate("sms_battle_13_0")
				},
			[13]	= {
				func = "spawn_restrictor.volna_btr2_sr1()",
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_14_0")
	    			}
		},
-- Волна: последняя битва, лагерь Изумрудное
		[45] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 12,
				tip = "%c[sender]"..translate("name_korshun")..":\\n%c[sms_red]"..translate("battle_zaton_45_2_0"),
				tip_snd = [[sms\korshun\battle_zaton_45_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_45_3_0"),
				tip_snd = [[sms\strelok\battle_zaton_45_3]],
			},
			[4]	= {
				timeout = 13,
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_15_0")
			},
			[5]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["bloodsucker_volna"] = 2
		 		}
			},
			[6]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["deathclaw_volna"] = 2
				}
			},
			[7]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 3,
					["deathclaw_volna"] = 2
				}
			},
			[8]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 4,
					["chimera_wolf_volna"] = 3,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 1
				}
			},
			[9]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 3
				}
			},
			[10]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 2
				}
			},
			[11]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 4,
					["bloodsucker_volna"] = 5,
					["deathclaw_volna"] = 3
				}
			},
			[12]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 1
		 		}
			},
			[13]	= {
				dist = 50,
				timeout = 20,
				enemy = {
					["volna_deathclaw"] = 1
		 		}
			},
			[14]	= {
				timeout = 12,
				tip = "%c[sender]"..translate("name_kruglov")..":\\n%c[sms_red]"..translate("battle_zaton_45_14_0"),
				tip_snd = [[sms\kruglov\battle_zaton_45_14]],
		},
			[15]	= {
				func = "spawn_restrictor.volna_btr3_sr1()",
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_16_0")
	    	}
		},
-- Волна: последняя битва, заправка
		[46] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_46_2_0"),
				tip_snd = [[sms\strelok\battle_zaton_46_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_17_0")
			},
			[4]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["bloodsucker_volna"] = 2
		 		}
			},
			[5]	= {
				dist = 80,
				timeout = 160,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["deathclaw_volna"] = 2
				}
			},
			[6]	= {
				dist = 80,
				timeout = 160,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 3,
					["deathclaw_volna"] = 2
				}
			},
			[7]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 4,
					["chimera_wolf_volna"] = 3,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 1
				}
			},
			[8]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 3
				}
			},
			[9]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 2
				}
			},
			[10]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 4,
					["bloodsucker_volna"] = 5,
					["deathclaw_volna"] = 3
				}
			},
			[11]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 1
		 		}
			},
			[12]	= {
				dist = 50,
				timeout = 100,
				enemy = {
					["volna_new_hell"] = 1
		 		}
			},
			[13]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_kapitan_filatov")..":\\n%c[sms_red]"..translate("sms_battle_18_0")
	    		},
			[14]	= {
				func = "akill.cap_filatov_spawn()"
	    		}
		},
-- Паучья сеть, взрываем бомбы
		[49] = {
			[1]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_49_1_0"),
				tip_snd = [[sms\strelok\battle_zaton_49_1]],
			},
			[2]	= {
				timeout = 6,
				func = "akill.nazar_spider_timer()"
			},
			[3]	= {
				timeout = 18,
				func = "akill.nazar_spider_bum()"
			},
			[4]	= {
				tip = "%c[sender]"..translate("name_nazar")..":\\n%c[sms_red]"..translate("battle_zaton_49_4_0"),
				tip_snd = [[sms\nazar\battle_zaton_49_4]],
				info = "nazar_spider_end"
			}
		},
-- Немецкий орден, немцы из тп
		[50] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 6,
				func = "akill.nazar_orden_flash()"
			},
			[3]	= {
				timeout = 15,
				tip = "%c[sender]"..translate("name_nazar")..":\\n%c[sms_red]"..translate("battle_zaton_50_3_0"),
				tip_snd = [[sms\nazar\battle_zaton_50_3]],
			},
			[4]	= {
				timeout = 15,
				func = "akill.orden_tp1()"
			},
			[5]	= {
				timeout = 20,
				func = "akill.orden_tp2()"
			},
			[6]	= {
				timeout = 20,
				func = "akill.orden_tp3()"
			},
			[7]	= {
				func = "akill.orden_tp2()"
			}
		},
-- Немецкий орден, немцы у Шевченко
		[51] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 6,
				func = "akill.nazar_orden_flash()"
			},
			[3]	= {
				timeout = 10,
				tip = "%c[sender]"..translate("name_nazar")..":\\n%c[sms_red]"..translate("battle_zaton_51_3_0"),
				tip_snd = [[sms\nazar\battle_zaton_51_3]],
			},
			[4]	= {
				timeout = 8,
				tip = "%c[sender]"..translate("name_mertsayuschii")..":\\n%c[sms_red]"..translate("battle_zaton_51_4_0"),
				tip_snd = [[sms\mercauschiy\battle_zaton_51_4]],
			},
			[5]	= {
				timeout = 20,
				func = "akill.orden_tp4()"
			},
			[6]	= {
				timeout = 25,
				func = "akill.orden_tp5()"
			},
			[7]	= {
				timeout = 25,
				func = "akill.orden_tp6()"
			},
			[8]	= {
				timeout = 25,
				func = "akill.orden_tp4()"
			},
			[9]	= {
				timeout = 25,
				func = "akill.orden_tp5()"
			},
			[10]	= {
				func = "akill.orden_tp6()"
			}
		},
-- Засада немцев у Изумрудного
		[52] = {
			[1]	= {
				timeout = 2
			},
			[2]	= {
				timeout = 5,
				func = "akill.nazar_orden_flash()"
			},
			[3]	= {
				timeout = 3,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_52_3_0"),
				tip_snd = [[sms\strelok\battle_zaton_52_3]],
			},
			[4]	= {
				func = "akill.zasada_vermaht_spawn()"
			}
		},
-- Защита госпиталя
		[53] = {
			[1]	= {
				timeout = 3,
			},
			[2]	= {
				timeout = 90,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_53_2_0"),
				tip_snd = [[sms\strelok\battle_zaton_53_2]],
				func = "akill.defend_hospital_spawn1()"
			},
			[3]	= {
				timeout = 100,
				func = "akill.defend_hospital_spawn2()"
			},
			[4]	= {
				timeout = 100,
				func = "akill.defend_hospital_spawn3()"
			},
			[5]	= {
				timeout = 100,
				func = "akill.defend_hospital_spawn1()"
			},
			[6]	= {
				timeout = 10,
				func = "akill.defend_hospital_spawn4()"
			},
			[7]	= {
				func = "akill.volna_day1_dogs()"
			}
		},
-- Подрыв гиганта
		[54] = {
			[1]	= {
				timeout = 17,
			},
			[2]	= {
				timeout = 5,
				tip = "%c[sender]"..translate("name_basti")..":\\n%c[sms_red]"..translate("battle_zaton_54_2_0"),
				tip_snd = [[sms\buusty\battle_zaton_54_2]], 
			},
			[3]	= {
				timeout = 1,
				func = "akill.gigant_swamp_bum()"
			},
			[4]	= {
				timeout = 5,
				func = "akill.gigant_swamp_kill()"
			},
			[5]	= {
				timeout = 7,
				info = "buusty_gigant_have"
			},
			[6]	= {
				dist = 65,
				tip = "%c[sender]"..translate("name_mechenii")..":\\n%c[sms_red]"..translate("battle_zaton_54_6_0"),
				tip_snd = [[sms\strelok\battle_zaton_54_6]], 
				enemy = {
					["molerat"] = 5,
					["nosales"] = 4,
					["kikimora"] = 5
				}
			}
		}
	}
-- Akill end
}

-- Основной обработчик. Вызывает сам себя через таймер. И первый запуск нужно делать тоже через таймер.
function show_must_go_on(params_string)
	local data = string.to_table(params_string)
	local lvl, btl, wave = data[1], tonumber(data[2]), tonumber(data[3])
	local cur_wave = battles[lvl][btl][wave]
	local pos, lv, sector
	--log("lvl: "..lvl..", btl: "..tostring(btl)..", wave: "..tostring(wave))
	
	-- сменили локу - битва закончена
    if level.name() ~= lvl then 
		show_off()
		return
	end

	sector = get_sector()
	give_info("battle")

	-- проверяем, не заныкался ли где гг в закутке - можно ли заспавнить на нормальном расстоянии от него
	if cur_wave.dist then
		pos, lv = get_pos(cur_wave.dist, sector)
		if pos:distance_to(db.actor:position()) < min_good_distance then
			-- заныкался - откладываем спавн, пока гг не выйдет из укрытия
			timer("battle", min_good_distance_timeout, {lvl, btl, wave})
			return
		end
	end
	
	-- спавн монстров/неписей
	if cur_wave["enemy"] then
		for s,p in pairs(cur_wave["enemy"]) do
			for i=1,p do
				pos, lv = get_pos(cur_wave.dist, sector)
				create(s, pos, lv, db.actor:game_vertex_id())
				monster_cnt = monster_cnt+1
			end
		end
	end

	if cur_wave.rest then
		-- есть перерыв

		if cur_wave.rukzak then
			-- есть тайник - спавним
			timer("battle_rest", math.random(cur_wave.timeout*0.8, cur_wave.timeout*1.2), {lvl, btl, wave, monster_cnt})
		end

		-- даем передышку
		cur_wave.timeout = cur_wave.timeout+rest_timeout
		monster_cnt = 0
	end

	if cur_wave.info then
		-- выдаем поршень
		give_info(cur_wave.info)
	end
	if cur_wave.func then
		-- выполняем функцию
		loadstring(cur_wave.func)()
	end
	if cur_wave.tip then
		-- выдаем смс
		sms(cur_wave.tip, nil, nil, 15000, nil, cur_wave.tip_snd)
	end

	-- следующая волна
	wave = wave+1
	if battles[lvl][btl][wave] then
		-- есть следующая волна - запускаем
		--log("lvl: "..lvl..", btl: "..tostring(btl)..", wave: "..tostring(wave))
		timer("battle", math.random(cur_wave.timeout*0.8, cur_wave.timeout*1.2), {lvl, btl, wave})
	else
		-- конец битвы
		show_off()
	end
end

-- подкрепление в виде рюкзака
-- текущая волна должна идти параметром приватно, т.к. наверху уже следующая волна на очереди
function reinforcement(params_string)
	local data = string.to_table(params_string)
	local lvl, btl, wave, last_monster_cnt = data[1], tonumber(data[2]), tonumber(data[3]), tonumber(data[4])
	local cur_wave = battles[lvl][btl][wave]
	local pos, lv

	-- сменили локу - битва закончена
    if level.name() ~= lvl then 
		show_off()
		return
	end
	
	-- рюкзак спавним с меткой и не далее 10 м от гг, чтобы нашел
	pos, lv = get_pos(math.random(3,10))
	local ruk = create("m_inventory_box_battle", pos, lv, db.actor:game_vertex_id())
	map_spot(ruk.id, "treasure", "reinforcement_0")
	--log("ruk.id: "..tostring(ruk.id))

	-- аптечки
	if cur_wave.medkit then
		--log("medkit")
		for i=1,math.random(0, cur_wave.medkit) do
			create(medkits[math.random(#medkits)], xyz(0,0,0), 0, 0, ruk.id)
		end
	end

	-- патроны/подствол
	local wpn, section, list
	if cur_wave.ammo or cur_wave.podstvol then
		for i=1,2 do
			if db.actor:item_in_slot(i) then
				wpn = db.actor:item_in_slot(i)
				
				if cur_wave.ammo then
					--log("ammo")
					for j=1,math.floor(last_monster_cnt*cur_wave.ammo) do
						list = rx_utils.parse_list(nil, wpn:section(), "ammo_class")
						section = table.random(list)
						ai:create_ammo(section, xyz(0,0,0), 0, 0, ruk.id, rx_utils.read_from_ini(nil, section, "box_size", 1, 3))
					end
				end
				
				if cur_wave.podstvol and rx_utils.addon_attached(wpn, "gl") then
					--log("podstvol")
					for j=1,math.floor(last_monster_cnt*cur_wave.podstvol) do
						list = rx_utils.parse_list(nil, wpn:section(), "grenade_class")
						section = table.random(list)
						create(section, xyz(0,0,0), 0, 0, ruk.id)
					end
				end
			end
		end
	end
	
	-- разный допхабар
	if cur_wave["items"] then
		for s,p in pairs(cur_wave["items"]) do
			for i=1,p do
				create(s, xyz(0,0,0), 0, 0, ruk.id)
			end
		end
	end

	-- выдаем смс
	if cur_wave.ruk_sms then
		sms(cur_wave.ruk_sms, nil, nil, 15000, nil, cur_wave.ruk_snd)
	end
end

-- выбор сектора для спавна
function get_sector()
	return math.random(1,3)*90
end

-- определение места спавна. параметры:
-- dist - расстояние от ГГ
-- sector - в каком секторе спавнить (сзади, справа, или слева) от ГГ. Сектор получать функцией get_sector(). Если не указан - выполняется рандомный спавн вокруг гг (не нужно указывать для рюкзаков)
-- Возвращает 2 значения: позицию спавна и левел_вертекс
function get_pos(dist, sector)
	local not_random_spawn = sector ~= nil
	if not sector then sector = math.random(360) end
	local pi2 = math.pi*2
	local math_pi_180 = 180/math.pi
	local dir = screen.cam_dir
	local actor_dir														-- вектор взгляда актора, выравненный горизонтально
	local actor_pos = db.actor:position()
	local actor_lv = db.actor:level_vertex_id()
	local pos															-- нужная нам позиция
	local dist_ok = 1.4													-- двойной шаг АИ сетки
	local vert_ok														-- ближайший подходящий вертекс, предложенный движком
	local pos_ok														-- позиция ближайшего подходящего вертекса
	local rotate_angle = math.asin(dist_ok/dist)						-- итератор вращения направления
	local actor_fov = math.rad(screen.fov/2)							-- угол обзора гг, если sector задан - то в видимой зоне не спавним
	local cur_angle = 0
	local cur_pos, cur_vert, cur_dist 
	local best_pos, best_dist											-- наилучшая найденная позиция

	-- выравниваем вектора по горизонтали
	dir = vector():set(dir.x,0,dir.z):normalize()
	actor_dir = dir
	
	-- ищем вертекс по сектору
	dir = vector_rotate_y(dir, sector)
	pos = vector():mad(actor_pos, dir, dist)
	vert_ok = level.vertex_in_direction(actor_lv, dir, dist)
	pos_ok = level.vertex_position(vert_ok)
	
	if not_random_spawn then 
		-- Не рандомый спавн вокруг - нужно искать поточнее в указанном секторе
	
		-- для начала исключаем очевидные случаи
		if pos:distance_to(pos_ok) < dist_ok or
			-- сплошная АИ сетка без препятствий - все нашлось само,
			actor_pos:distance_to(pos_ok) > dist then
			-- либо актор далеко за аи сеткой - спавним в ближайшем подходящем вертексе.
		else
			-- несплошная АИ сетка или препятствия - ищем вариант получше

			-- выставляем направление вращения
			if math.random() < 0.5 then
				rotate_angle = -rotate_angle
			end
			
			-- продолжим искать от ближайшего предложенного движком вертекса в нужном нам направлении
			best_pos = pos
			best_dist = dist
			repeat
				-- поворачиваем направление поиска
				cur_angle = cur_angle+rotate_angle
				dir = vector_rotate_y(dir, rotate_angle*math_pi_180)

				if math.acos(actor_dir:dotproduct(dir)) > actor_fov then
					-- подходящий угол, ищем вертекс
					pos = vector():mad(actor_pos, dir, dist)
					cur_vert = level.vertex_in_direction(actor_lv, dir, dist)
					cur_pos = level.vertex_position(cur_vert)
					cur_dist = pos:distance_to(cur_pos)
					if cur_dist < dist_ok and no_anomaly_in(cur_pos) then
						-- нашли вертекс - выходим
						pos_ok = cur_pos
						vert_ok = cur_vert
						break
					end
					-- точного попадания пока нет - выбираем ближайший по расстоянию вертекс
					if cur_dist < best_dist and no_anomaly_in(cur_pos) then
						best_pos = cur_pos
						best_dist = cur_dist
						pos_ok = cur_pos
						vert_ok = cur_vert
					end
				end
			until math.abs(cur_angle) > pi2
			-- обернулись вокруг - точного попадания нет, используем ближайший к точке
		end
	end

	return pos_ok, vert_ok
end

function show_off()
	monster_cnt = 0
	disable_info("battle")
end

-- "быстрый" уборщик
-- ускоренное удаление трупов при очень больших битвах. вызывается из апдейта монстров
function cleanup(obj)
    if has_info("battle") and (not obj:alive()) and db.actor:position():distance_to(obj:position()) > cleanup_distance then
		release(server_object(obj:id()), true)
	end
end

-- проверка попадания точки спавна в аномалию
function no_anomaly_in(pos)
	local anom_id,anom_pos,anom_radius,dist = amk_anoms.get_nearest_anomaly_for_pos(pos)
	return not anom_id or dist-anom_radius > 5
end

